---
permalink: rhel-install/concept-unsupported-features-for-wfa-on-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, limitations 
summary: OnCommand Workflow Automation （ WFA ） 5.1 には、 WFA をインストールして設定する前に注意しておく必要がある制限事項とサポートされない機能がいくつか含まれています。 
---
= OnCommand Workflow Automation の既知の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ） 5.1 には、 WFA をインストールして設定する前に注意しておく必要がある制限事項とサポートされない機能がいくつか含まれています。

* * LDAP 認証 *
+
** LDAP 認証に使用できるのは、 Microsoft Active Directory の Lightweight Directory Access Protocol （ LDAP ）サーバのみです。
** LDAP 認証を使用するには、 LDAP グループのメンバーである必要があります。
** 認証または通知に、複数のドメインの階層構造に含まれる LDAP ユーザ名は使用しないでください。




[NOTE]
====
Microsoft Active Directory ライトウェイトディレクトリサービス (AD LDS) はサポートされていません。

====
* * WFA のデータソースの種類 *
+
OnCommand Unified Manager 6.0 、 6.1 、 6.2 のデータソースタイプは WFA 4.1 リリースで廃止されました。これらのデータソースタイプは今後のリリースでサポートされなくなります。

* * WFA は Linux * にインストールされています
+
** Data ONTAP 7-Mode の認定コンテンツは現在提供されていません。
** PowerShell コードのみを含むコマンドは、 Linux と互換性がありません。
** 7-Mode と VMware 向けに認定されているコマンドは現在 Perl には移植されていないため、 Linux との互換性はありません。


* * カテゴリ名の作成 *
+
** カテゴリ名にハイフン (-) を使用すると、カテゴリが保存されるとスペースに置き換えられます。たとえば、カテゴリ名「 abc-xyz 」を指定すると、カテゴリ名は「 abc xyz 」として保存され、ハイフンは削除されます。この問題 を回避するために、カテゴリ名にハイフンを使用しないでください。
** カテゴリ名にコロン（ : ）が使用されている場合、カテゴリが保存されると、コロンの前のテキスト文字列は無視されます。たとえば、「 abc ： xyz 」というカテゴリ名が指定されている場合、カテゴリ名は「 xyz 」として保存され、「 abc 」という文字列は削除されます。この問題 を避けるため、カテゴリ名にはコロンを使用しないでください。
** 2 つのカテゴリの名前が同じであることを防ぐチェックはありません。ただし、ナビゲーションペインからこれらのカテゴリを選択すると問題が発生します。この問題 を回避するには、各カテゴリ名が一意であることを確認してください。



