---
permalink: rhel-install/task-create-a-certificate-signing-request-for-workflow-automation-linux.html 
sidebar: sidebar 
keywords: workflow, automation, wfa, linux, create, certificate, sign, request 
summary: Linux で証明書署名要求（ CSR ）を作成すると、 Workflow Automation （ WFA ）のデフォルトの SSL 証明書ではなく、認証局（ CA ）が署名した SSL 証明書を使用できるようになります。 
---
= Workflow Automation の証明書署名要求を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux で証明書署名要求（ CSR ）を作成すると、 Workflow Automation （ WFA ）のデフォルトの SSL 証明書ではなく、認証局（ CA ）が署名した SSL 証明書を使用できるようになります。

* WFA をインストールした Linux システムに対する root 権限が必要です。
* WFA のデフォルトの SSL 証明書を置き換えておく必要があります。


WFA のデフォルトのインストールパスは、この手順 で使用されます。インストール時にデフォルトパスを変更した場合は、カスタムの WFA インストールパスを使用する必要があります。

.手順
. WFA ホストマシンに root ユーザとしてログインします。
. WFA サーバでシェルプロンプトを開き、 <OpenJDK のインストール先 >/bin にディレクトリを変更します
. CSR ファイルを作成します。
+
keytool -certreq -keystore wfa_install_location WFA/jboss/standalone/configuration /keystore/wfa_keystore -alias "ssl keystore" -file /root/file_name .csr`

+
file_name は CSR ファイル名です。

. プロンプトが表示されたら、パスワードを入力します（デフォルトまたは新規）。
+
デフォルトのパスワードは、ランダムに生成された暗号化パスワードです。

+
デフォルトのパスワードを取得して復号化するには、ナレッジベースの記事の手順を使用します link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["WFA 5.1.1.0.4の自己署名証明書を更新する方法"^]

. file_name .CSR ファイルを CA に送信して署名済み証明書を取得します。
+
詳細については、 CA の Web サイトを参照してください。

. CA からチェーン証明書をダウンロードし、チェーン証明書をキーストアにインポートします。
+
keytool -import -alias "ssl keystore wfa_install_location /wfa/standalone/configuration /keystore.keystore"-trustcacerts -file chain_cert.cer

+
「chain_cert.cer」は、CAから受信したチェーン証明書ファイルです。ファイルは X.509 形式である必要があります。

. CA から受け取った署名済み証明書をインポートします。
+
keytool -import -alias "ssl keystore"-keystore wfa_install_location /wfa/standalone/configuration /keystore.keystore "-trustcacerts-file certificate.cer

+
「certificate.cer」は、CAから受信したチェーン証明書ファイルです。

. WFA のサービスを開始します。
+
`./wfa -- start=db`

+
`./wfa -- start=wfa


