---
permalink: windows-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html 
sidebar: sidebar 
keywords: back up, oncommand, workflow, automation, database 
summary: OnCommand Workflow Automation （ WFA ）データベースのバックアップには、システムの設定と、プレイグラウンドデータベースなどのキャッシュ情報が含まれます。バックアップは、同じシステムまたは別のシステムでのリストア目的で使用できます。 
---
= OnCommand Workflow Automation データベースをバックアップしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）データベースのバックアップには、システムの設定と、プレイグラウンドデータベースなどのキャッシュ情報が含まれます。バックアップは、同じシステムまたは別のシステムでのリストア目的で使用できます。

データベースの自動バックアップは、毎日午前 2 時に作成されますファイルは .zip ファイルとして wfa_install_location /wfa_Backups に保存されます。

WFA は、 wfs-Backups ディレクトリに最大 5 つのバックアップを保存し、最も古いバックアップを最新のバックアップに置き換えます。WFA をアンインストールしても、 wfs-Backups ディレクトリは削除されません。WFA のアンインストール時に WFA データベースのバックアップを作成しなかった場合は、自動的に作成されたバックアップをリストアに使用できます。

また、リストアのために特定の変更を保存する必要がある場合に、 WFA データベースを手動でバックアップすることもできます。たとえば、自動バックアップの実行前に行った変更をバックアップする場合などです。

[NOTE]
====
* WFA のデータベースバックアップは、同じバージョンかそれ以降のバージョンの WFA を実行しているシステムにのみリストアできます。
+
たとえば、 WFA 4.2 を実行しているシステムで作成したバックアップは、 WFA 4.2 以降を実行しているシステムにのみリストアできます。

* ハイアベイラビリティ構成では、ディザスタリカバリ時に Web UI を使用して WFA データベースをバックアップすることはできません。


====


== ユーザクレデンシャルのバックアップとリストア

WFA データベースのバックアップには、 WFA ユーザクレデンシャルが含まれます。


NOTE: WFA データベースは AutoSupport データにも含まれていますが、 WFA ユーザのパスワードは AutoSupport データには含まれていません。

WFA データベースをバックアップからリストアしても、次の項目は保持されます。

* 現在の WFA のインストール時に作成された管理者ユーザクレデンシャル。
* デフォルトの admin ユーザ以外の admin 権限を持つユーザがデータベースをリストアする場合は、両方の admin ユーザのクレデンシャルが必要になります。
* 現在の WFA インストール環境のその他すべてのユーザクレデンシャルは、バックアップのユーザクレデンシャルに置き換えられます。

