---
permalink: windows-install/task-configure-wfa-with-mscs-using-configuration-scripts.html 
sidebar: sidebar 
keywords: configure, workflow, automation, mscs 
summary: MSCS （ Microsoft クラスタサーバ）に Workflow Automation （ WFA ）をインストールしたら、設定スクリプトを使用して MSCS でハイアベイラビリティを実現するように WFA を設定する必要があります。 
---
= MSCS で Workflow Automation を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MSCS （ Microsoft クラスタサーバ）に Workflow Automation （ WFA ）をインストールしたら、設定スクリプトを使用して MSCS でハイアベイラビリティを実現するように WFA を設定する必要があります。

WFA のバックアップを作成しておく必要があります。


NOTE: 設定を開始する前に、両方の MSCS クラスタノードで WFA 暗号化キーが一貫して設定されていることを確認してください。両方のノードに設定されていない場合は、フェイルオーバーが発生すると、クレデンシャルを 2 つ目のノードで復号化できず、ワークフローが失敗します。

.手順
. MSCS クラスタの最初のノードにログインし、次の手順を実行します。
+
[cols="2*"]
|===
| 用途 | 手順 


 a| 
Windows 2012 、 Windows 2016 、 Windows 2019
 a| 
.. フェイルオーバークラスタマネージャで、 * サービスロール * を右クリックします。
.. [ 空のサービスロールの作成 *] を選択し、ロールの名前を「 wfa 」に変更します。
.. 新しく作成した「 wfa 」ロールに IP アドレスリソースを追加します。
+
... フェイルオーバー・クラスタ・マネージャで、新しく作成した「 wfa 」ロールを右クリックします。
... [ * リソース * > * その他のリソース * > * IP アドレス * ] を選択します。
... クラスタの IP アドレスを設定




|===
. 「 MSCS _data_parameters.xml 」ファイルを編集し、 MySQL データ・ディレクトリへの相対パスを設定します。
+
[listing]
----
<dir>
    <description>Data directory</description>
    <srcpath>..\..\..\..\..\ProgramData\MySQL\MySQLServerData</srcpath>
    <destpath>wfa</destpath>
</dir>
----
. 「 MSCS _resource_properties.xml 」ファイルを編集し、次の更新を行います。
+
.. 「 NA_wfa_DB 」サービス名の検索 / 置換を実行し、それを「 MYSQL57 」に更新します。
.. 「 vip_res 」を仮想 IP アドレス名に設定します。
+
[listing]
----
<resource>
    <type>essential</type>
    <id>vip_res</id>
    <prettyname>WFA IP address</prettyname>
</resource>
----
.. 'data_res <prettyname>' を共有ディスクリソースに割り当てられているディスク名に設定します
+
[listing]
----
<resource>
    <type>essential</type>
    <id>datadisk_res</id>
    <prettyname>Cluster Disk 2</prettyname>
</resource>
----
.. XML ファイルを最初のノードから 2 番目のノードにコピーします。
+
「コピー」「 \\node1\D$\Program Files\NetApp\wfa\bin\ha\*xml 」「 D ： \Program Files\NetApp\wfa\bin\ha 」

.. コマンドを実行して 2 つ目のノードをクラスタに追加します。
+
D:\Program Files\NetApp\WFA\bin\HA>perl ha_setup.pl --join-t MSCS -f E:\`



. コマンドプロンプトで、 ha_setup.pl スクリプトを実行して WFA のデータを共有の場所に移動し、フェイルオーバー用に WFA を設定します。このスクリプトは、 wfa_install_location WFA\bin\ha\ にあります。
+
`perl ha_setup.pl --first [-t type_of _cluster_vcs][-g cluster_group_name [-i ip_address_name][-n cluster_name] [-k shared_disk_resource_name] [-f shared_drive_path]

+
ha_setup.pl スクリプトでは 'MSCS クラスタの IP アドレスリソースを使用して入力を行う必要がありますMSCS 2016 にインストールする場合は、 IP アドレス「 WFA の IP アドレス」ではなく、名前を付けてリソースを追加する必要があります。例：

+
perl ha_setup.pl -- first-t MSCS -g WFA -i "WFA IP address" -n wfa_cluster -k "Cluster Disk 2" -f E: \

. 出力で正常に設定されたメッセージを確認して、 MSCS リソースが作成されていることを確認します。
+
[listing]
----
Successfully configured MSCS cluster resources on this node
----
. フェイルオーバークラスタマネージャから WFA サービスを停止します。
+
[cols="2*"]
|===
| 用途 | 手順 


 a| 
Windows 2012 、 Windows 2016 、 Windows 2019
 a| 
.. 「 * Service Roles * 」を選択し、新しく作成した「 WFA 」ロールを選択します。
.. リソースペインで * MYSQL57* を右クリックし、 * オフラインにする * を選択します。
.. リソースペインで、 * na_wfa_SRV* を右クリックし、 * オフラインにする * を選択します。


|===


WFA データベースサービスと WFA サーバサービスをオフラインにする必要があります。WFA のサービスを Windows サービスから停止しないでください。

. WFA リソースをセカンダリノードに手動で移動します。
. 共有ディスクに 2 つ目のノードからアクセスできることを確認します。
. コマンドプロンプトで、クラスタのセカンダリノードで ha_setup.pl スクリプトを実行し、共有の場所からデータを使用するように WFA を設定します。
+
`perl ha_setup.pl -- join[-t type_OF_cluster_MSCS] [-f shared_drive_path

+
ha_setup.pl スクリプトは、 wfa_install_location WFA\bin\ha\ にあります。

+
`perl ha_setup.pl -- join-t MSCS -f E:

. フェイルオーバークラスタマネージャから、 WFA リソースをオンラインにします。
+
[cols="2*"]
|===
| 用途 | 手順 


 a| 
Windows 2012 、 Windows 2016 、 Windows 2019
 a| 
.. 新しく作成した「 wfa 」ロールを右クリックし、「 Start Role 」を選択します。ロールのステータスは running である必要があります。また、個々のリソースは Online 状態である必要があります。


|===
. MSCS クラスタの 2 つ目のノードに手動で切り替えます。
. クラスタの 2 つ目のノードで WFA サービスが正常に開始されることを確認します。

