---
permalink: windows-install/task-back-up-regular-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, back up, regular, wfa, database, cli 
summary: OnCommand Workflow Automation （ WFA ）データベースの定期バックアップは、 WFA コマンドラインインターフェイス（ CLI ）を使用して実行できます。通常のバックアップでは、 WFA データベースのみがバックアップされます。 
---
= CLI を使用して WFA データベースを（通常の）バックアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）データベースの定期バックアップは、 WFA コマンドラインインターフェイス（ CLI ）を使用して実行できます。通常のバックアップでは、 WFA データベースのみがバックアップされます。

管理者ユーザクレデンシャル、アーキテクトクレデンシャル、またはバックアップユーザクレデンシャルが必要です。

ハイアベイラビリティ環境では、 REST API を使用してスケジュールされたバックアップを作成する必要があります。WFA がフェイルオーバーモードの場合、 CLI を使用してバックアップを作成することはできません。

詳細については、 REST のドキュメントを参照してください。

.手順
. シェルプロンプトで、 WFA サーバの「 wfa_install_location \ wfa \bin. 」ディレクトリに移動します
+
wfa_install_location には、 WFA のインストールディレクトリを指定します。

. WFA データベースをバックアップします。
+
`..\wfa --backup --user=user [--password=pass][--location=path]'

+
** user は、バックアップユーザのユーザ名です。
** password はバックアップユーザのパスワードです。
+
パスワードを指定していない場合は、プロンプトが表示されたらパスワードを入力する必要があります。

** path は、バックアップファイルの完全なディレクトリパスです。


. 指定した場所にバックアップファイルが作成されたことを確認します。

