---
permalink: windows-install/task-restore-full-the-oncommand-workflow-automation-database-using-rest-apis.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, restore, wfa, database, rest, apis 
summary: REST API を使用して、 OnCommand Workflow Automation （ WFA ）データベースの完全なリストアを実行できます。フルリストアでは、 WFA データベース、 WFA 設定、およびキーをリストアできます。 
---
= REST API を使用して WFA データベースをリストア（フル）します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST API を使用して、 OnCommand Workflow Automation （ WFA ）データベースの完全なリストアを実行できます。フルリストアでは、 WFA データベース、 WFA 設定、およびキーをリストアできます。

* WFA データベースの .zip バックアップを作成しておく必要があります。
* 管理者またはアーキテクトのクレデンシャルが必要です。
* 手順 移行の一環としてデータベースをリストアする場合は、フルリストアを実行する必要があります。


.手順
. REST クライアントブラウザに次の URL を入力します。「 + https://IP address of WFA server/rest/backups ？ full=true+`
. [ バックアップ ] ウィンドウで、 *POST* メソッドを選択します。
. [* Part*] ドロップダウンリストで、 [* Multipart Body] を選択します。
. ［ * ファイル * ］ フィールドに、次の情報を入力します。
+
.. [ コンテンツタイプ * （ Content type * ） ] ドロップダウンリストで、 [ * 複数パーツ / フォームデータ * （ * multi-ppart/form-data* ） ] を選択します。
.. [* Charset * （文字セット * ） ] ドロップダウンリストで、 [* ISO-8859-1 * ] を選択します。
.. [ * ファイル名 * ] フィールドに、作成したバックアップ・ファイルの名前を入力し、リストアします。
.. [* 参照 ] をクリックします。
.. .zip バックアップファイルの場所を選択します。


. wfa_install_location WFA\bin ディレクトリに移動し、 WFA サービスを再起動します。
. NetApp WFA Database * サービスと NetApp WFA Server * サービスを再起動します。
+
wfa -- 再起動

. リストア処理が成功し、 WFA にアクセスできることを確認してください。

