---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password policy, windows 
summary: OnCommand Workflow Automation （ WFA ）は、ローカルユーザにパスワードポリシーを適用します。デフォルトのパスワードポリシーを変更して、要件に応じてパスワードを設定できます。 
---
= Windows のデフォルトパスワードポリシーを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）は、ローカルユーザにパスワードポリシーを適用します。デフォルトのパスワードポリシーを変更して、要件に応じてパスワードを設定できます。

WFA ホストシステムに root ユーザとしてログインする必要があります。

* WFA のデフォルトのインストールパスは、この手順 で使用されます。
+
インストール時にデフォルトの場所を変更した場合は、カスタムの WFA インストールパスを使用する必要があります。

* デフォルトのパスワードポリシーを変更するコマンドは、 .\wfa --password-policy = default です。
+
デフォルト設定は、 "minLength=true,8;specialChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whitespaceChar=false`" です。デフォルトのパスワードポリシーのこの設定では、パスワードは 8 文字以上にする必要があり、特殊文字、数字、小文字、大文字をそれぞれ 1 文字以上含める必要があります。また、スペースを含めることはできません。



.手順
. コマンドプロンプトで、 WFA サーバの次のディレクトリに移動します。
+
wfa_install_location /wfa/bin/

. デフォルトのパスワードポリシーを変更します。
+
`..\wfa -- password-policy=PasswordPolicyString -- restart=wfa


