---
permalink: help/concept-how-you-define-workflows.html 
sidebar: sidebar 
keywords: goal, workflow, steps, execute, arrange, complete, workflow 
summary: ワークフローの目標を、ワークフローで実行する必要がある手順に分割する必要があります。その後、ワークフローを完了するための手順を並べ替えることができます。 
---
= ワークフローを定義する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークフローの目標を、ワークフローで実行する必要がある手順に分割する必要があります。その後、ワークフローを完了するための手順を並べ替えることができます。

ワークフローとは、エンドツーエンドのプロセスを実行するために必要な一連のステップを含むアルゴリズムです。プロセスの範囲は、ワークフローの目標によって異なる場合があります。ワークフローの目的は、ストレージの運用のみ、またはネットワーク、仮想化、 IT システム、その他のアプリケーションを 1 つのプロセスの一部として処理するなど、より複雑なプロセスを処理することにあります。OnCommand Workflow Automation （ WFA ）ワークフローはストレージアーキテクトが設計し、ストレージオペレータが実行します。

ワークフローを定義するには、ワークフローの目標を一連の手順に分けます。たとえば、 NFS ボリュームを作成するには、次の手順を実行します。

. ボリュームオブジェクトの作成
. 新しいエクスポートポリシーを作成し、そのポリシーをボリュームに関連付けます


ワークフローの各ステップには、 WFA コマンドまたはワークフローを使用できます。WFA には、ストレージの一般的なユースケースに基づく、事前定義されたコマンドとワークフローが用意されています。特定の手順に使用できる定義済みのコマンドまたはワークフローが見つからない場合は、次のいずれかを実行できます。

* 手順に最も近い事前定義されたコマンドまたはワークフローを選択し、要件に応じて事前定義されたコマンドまたはワークフローをクローニングして変更します。
* 新しいコマンドまたはワークフローを作成します。


その場合は、新しいワークフローにコマンドやワークフローを配置して、目的を達成するためのワークフローを作成できます。

ワークフローの実行が開始されると、 WFA は実行を計画し、ワークフローとコマンドの入力を使用してワークフローを実行できることを確認します。ワークフローを計画すると、すべてのリソース選択とユーザ入力が解決され、実行計画が作成されます。計画が完了すると、 WFA は実行計画を実行します。実行計画は、一連の WFA コマンドと該当するパラメータで構成されます。
