---
permalink: help/concept-what-return-parameters-are.html 
sidebar: sidebar 
keywords: return, parameter, available, planning, phase, workflow, values, return, debugging, understand 
summary: 戻りパラメータは、ワークフローの計画フェーズのあとに使用できるパラメータです。これらのパラメータから返される値は、ワークフローのデバッグに役立ちます。戻りパラメータの仕組みと、デバッグワークフローへの戻りパラメータとして使用できるパラメータについて理解しておく必要があります。 
---
= 戻りパラメータの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
戻りパラメータは、ワークフローの計画フェーズのあとに使用できるパラメータです。これらのパラメータから返される値は、ワークフローのデバッグに役立ちます。戻りパラメータの仕組みと、デバッグワークフローへの戻りパラメータとして使用できるパラメータについて理解しておく必要があります。

ワークフローでは、変数属性、式、ユーザ入力値などの一連のパラメータを戻りパラメータとして指定できます。ワークフローの実行中に、指定したパラメータの値が計画フェーズで入力され、ワークフローの実行が開始されます。これらのパラメータの値は、ワークフローのその特定の実行での計算方法で返されます。ワークフローをデバッグする場合は、パラメータから返された値を参照します。

ワークフロー内の必須の戻りパラメータを指定すると、これらのパラメータの計算値または選択した値を確認できます。たとえば ' リソース選択ロジックを使用してワークフロー内のアグリゲートを選択する場合 ' 戻りパラメータとして 'aggregate' を指定すると ' ワークフローの計画中にどのアグリゲートが選択されたかを確認できます

ワークフローをデバッグするための戻りパラメータの値を参照する前に、ワークフローの実行が完了していることを確認する必要があります。戻りパラメータの値は、ワークフローの実行ごとに設定されます。ワークフローをいくつか実行したあとに戻りパラメータを追加した場合、そのパラメータの値は、パラメータの追加後にのみ実行できます。



== 戻りパラメータとして使用できるパラメータ

[cols="2*"]
|===
| パラメータを返します | 例 


 a| 
スカラである変数属性
 a| 
「ボリューム名」変数の属性である volume1.name,`



 a| 
定数
 a| 
max_volume_size



 a| 
ユーザ入力
 a| 
$clusterName の略



 a| 
変数属性、定数、およびユーザー入力を含む MVEL 式
 a| 
volume1.name+'-'+$clusterName



 a| 
コマンドの実行時に追加する戻りパラメータ
 a| 
PowerShell コマンドで次の行を使用すると、 $volumeUUID パラメータが戻りパラメータとして追加されます。 Add-WfaWorkflowParameter -Name "VolumeUUID" -value "`12345"-AddAsReturnParameter $true

|===


== 定義済みワークフローの戻りパラメータの例

戻りパラメータの指定方法を理解するには、 Designer で次の定義済みワークフローを開き、指定した戻りパラメータを確認します。

* vFiler に NFS ボリュームを作成します
* vFiler に qtree CIFS 共有を作成します
* clustered Data ONTAP ボリュームの CIFS 共有を作成

