---
permalink: help/concept-how-entity-versioning-works.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, wfa, entity, command, version, manage, change 
summary: コマンドやワークフローなどの OnCommand Workflow Automation エンティティはバージョン管理されています。バージョン番号を使用すると、 WFA エンティティに対する変更を簡単に管理できます。 
---
= エンティティのバージョン管理の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドやワークフローなどの OnCommand Workflow Automation エンティティはバージョン管理されています。バージョン番号を使用すると、 WFA エンティティに対する変更を簡単に管理できます。

各 WFA エンティティには、「 major.minor.revision 」形式のバージョン番号が含まれています。たとえば、 1.1.20 です。バージョン番号の各部分に最大 3 桁を含めることができます。

WFA エンティティのバージョン番号を変更する前に、次のルールを確認しておく必要があります。

* バージョン番号を現在のバージョンから以前のバージョンに変更することはできません。
* バージョンの各部分は、 0~999 の数値である必要があります。
* 新しい WFA エンティティは、デフォルトでは 1.0 にバージョン管理されます。
* エンティティのバージョン番号は、クローン作成時、または * 名前を付けて保存 * を使用してエンティティのコピーを保存するときに保持されます。
* WFA インストールには、エンティティの複数のバージョンを存在させることはできません。


WFA エンティティのバージョンを更新すると、その親エンティティのバージョンが自動的に更新されます。たとえば、 * Create Volume * コマンドのバージョンを更新すると、 * Create an NFS Volume * ワークフローが * Create Volume * コマンドの直下の親エンティティであるため、 * Create Volume * コマンドのバージョンが更新されます。バージョンの自動更新は、次のように適用されます。

* エンティティのメジャーバージョンを変更すると、その直後の親エンティティのマイナーバージョンが更新されます。
* エンティティのマイナーバージョンを変更すると、その直後の親エンティティのリビジョンバージョンが更新されます。
* エンティティのリビジョンバージョンを変更しても、その直後の親エンティティのバージョンの一部は更新されません。


次の表に、 WFA のエンティティとそのすぐ上の親エンティティを示します。

[cols="2*"]
|===
| エンティティ（ Entity ） | 即時親エンティティ 


 a| 
キャッシュクエリ
 a| 
* データソースのタイプ




 a| 
テンプレート
 a| 
* ワークフロー




 a| 
機能
 a| 
* ワークフロー
* テンプレート



NOTE: 関数に特殊文字または大文字と小文字が混在している場合、そのすぐ上の親エンティティのバージョンは更新されない可能性があります。



 a| 
辞書
 a| 
* テンプレート
* フィルタ
* キャッシュクエリ
* コマンドを実行します
* スクリプトメソッドを使用するデータソースのタイプ




 a| 
コマンドを実行します
 a| 
* ワークフロー




 a| 
フィルタ
 a| 
* ファインダ
* ワークフロー




 a| 
ファインダ
 a| 
* ワークフロー




 a| 
データソースのタイプ
 a| 
なし



 a| 
ワークフロー
 a| 
なし

|===
WFA では、バージョン番号の一部または完全なバージョン番号を使用してエンティティを検索できます。

親エンティティを削除した場合、子エンティティは保持され、削除のためにそのバージョンは更新されません。



== エンティティをインポートする際のバージョン管理の仕組み

Workflow Automation 2.2 より前のバージョンからエンティティをインポートする場合、エンティティのバージョンはデフォルトで 1.0.0 になります。インポートしたエンティティがすでに WFA サーバに存在する場合は、インポートしたエンティティで既存のエンティティが上書きされます。

インポート時に WFA エンティティに変更される可能性がある項目を次に示します。

* エンティティのアップグレード
+
エンティティは新しいバージョンで置き換えられます。

* エンティティのロールバック
+
エンティティは以前のバージョンで置き換えられます。

+

NOTE: エンティティのロールバックを実行すると ' そのすぐ上の親エンティティのバージョンが更新されます

* 新しいエンティティのインポート



NOTE: .dar ファイルからエンティティを選択的にインポートすることはできません

新しいバージョンのエンティティをインポートすると、その直後の親エンティティのバージョンが更新されます。

インポートされた親エンティティに複数の子エンティティがある場合、子エンティティに対する最高レベルの変更（メジャー、マイナー、またはリビジョン）のみが親エンティティに適用されます。次の例では、このルールの仕組みについて説明します。

* インポートされた親エンティティの場合、マイナー変更のある子エンティティとリビジョン変更のある子エンティティが存在する場合、マイナー変更が親エンティティに適用されます。
+
親のバージョンのレビジョン部分が増分されます。

* インポートされた親エンティティの場合、メジャー変更を持つ子エンティティが 1 つ存在し、マイナー変更を持つ子エンティティが別の子エンティティである場合、親エンティティにメジャー変更が適用されます。
+
親のバージョンのマイナー部分が増分されます。





== インポートされた子エンティティのバージョンが親のバージョンに与える影響の例

WFA で次のワークフローを考慮してください。 "`Create Volume and export using NFS-Custom`" 1.0.0"

ワークフローに含まれる既存のコマンドは次のとおりです。

* 「エクスポートポリシーの作成 - カスタム」 1.0.0
* 「ボリュームの作成 - カスタム」 1.0.0


インポートする .dar ファイルに含まれるコマンドは次のとおりです。

* 「エクスポートポリシーの作成 - カスタム」 1.1.0
* 「ボリュームの作成 - カスタム」 2.0.0


この .dar ファイルをインポートすると 'NFS-Custom' ワークフローを使用したボリュームの作成とエクスポートのマイナーバージョンが 1.1.0 に増加します
