---
permalink: help/concept-what-conditional-execution-is.html 
sidebar: sidebar 
keywords: condition, execution, help, design, workflow, commands, specified, conditions 
summary: 条件付き実行は、指定された条件が満たされたときにコマンドを実行できるワークフローを設計するのに役立ちます。 
---
= 条件付き実行とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
条件付き実行は、指定された条件が満たされたときにコマンドを実行できるワークフローを設計するのに役立ちます。

ワークフロー内のコマンドの実行は動的に実行できます。各コマンドの実行条件、またはワークフロー内のコマンド行を指定できます。たとえば ' 特定のデータセットが検出された場合にのみ ' Add volume to dataset' コマンドを実行し ' データセットが見つからない場合にワークフローを失敗させないようにすることができますこの場合は、「 Add volume to dataset 」コマンドを有効にして特定のデータセットを検索し、見つからない場合はワークフローでコマンドを無効にできます。

コマンドの条件付き実行のオプションは ' 辞書オブジェクトタブ ' およびパラメータのコマンド用パラメータダイアログの詳細タブで使用できます

ワークフローを中止したり、ワークフロー内の特定のコマンドを無効にしたりできます。また、次のいずれかのオプションを使用して実行するようにコマンドを設定することもできます。

* 条件なし
* 指定した変数が見つかった場合
* 指定した変数が見つからない場合
* 指定した式が true の場合


また、特定の時間間隔を待機するようにコマンドを設定することもできます。



== 定義済みワークフローでの条件付き実行の例

Designer で次の定義済みワークフローのコマンド詳細を開き、コマンドの条件付き実行の使用方法を理解できます。

* 基本的な clustered Data ONTAP ボリュームを作成
* clustered Data ONTAP の NFS ボリュームを作成

