---
permalink: help/reference-edit-pack-dialog-box.html 
sidebar: sidebar 
keywords: edit, pack, dialog, enable 
summary: パックの編集（ Edit Pack ）ダイアログボックスでは、パックを編集できます。 
---
= パックの編集ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パックの編集（ Edit Pack ）ダイアログボックスでは、パックを編集できます。

* [ 詳細 ] タブ
* パック内容タブ




== [ 詳細 ] タブ

* * 名前 *
+
名前を入力し、パックを保存できます。

* * バージョン *
+
バージョンを入力してパックを保存できます。

* * 作成者 *
+
作成者の名前を入力し、パックを保存できます。

* * 概要 *
+
概要 を入力してパックを保存できます。





== パック内容タブ

* * ワークフロー *
+
[ * ワークフロー * （ * Workflow * ） ] オプションを使用すると、ワークフローの * 名前 * と * エンティティバージョン * を表示できます。

* * ファインダ *
+
* ファインダ * オプションを使用すると、 Finder の * 名前 * と * エンティティバージョン * を表示できます。

* * フィルター *
+
[ * フィルタ * （ * Filters * ） ] オプションを使用すると、フィルタの * 名前 * および * エンティティバージョン * を表示できます。

* * コマンド *
+
コマンド * オプションを使用すると、コマンドの * 名前 * および * エンティティバージョン * を表示できます。

* * 関数 *
+
関数 * オプションを使用すると、関数の * 名前 * および * エンティティバージョン * を表示できます。

* * テンプレート *
+
[ * テンプレート * （ Templates * ） ] オプションを使用すると、テンプレートの * 名前 * および * エンティティバージョン * を表示できます。

* * 辞書 *
+
* 辞書 * オプションを使用すると、辞書の * 名前 * と * エンティティバージョン * を表示できます。

* * スキーム *
+
[ * スキーム * （ * Schemes * ） ] オプションを使用すると、スキームの * 名前 * と * エンティティバージョン * を表示できます。

* * キャッシュクエリ *
+
キャッシュクエリ * オプションを使用すると、キャッシュクエリの * 名前 * と * エンティティバージョン * を表示できます。

* * SQL データソースの種類 *
+
SQL データソースタイプ * オプションを使用すると、 SQL データソースタイプの * 名前 * および * エンティティバージョン * を表示できます。

* * スクリプトデータソースタイプ *
+
* スクリプトデータソースタイプ * オプションを使用すると、スクリプトデータソースタイプの * 名前 * および * エンティティバージョン * を表示できます。

* * カテゴリ *
+
[ カテゴリ * （ Categories * ） ] オプションを使用すると、カテゴリの * 名前 * および * エンティティバージョン * を表示できます。

* * リモートシステムタイプ *
+
* リモート・システム・タイプ * オプションを使用すると、リモート・システム・タイプの * 名前 * および * エンティティ・バージョン * を表示できます。





== コマンドボタン

* * 保存 *
+
パックを保存してダイアログボックスを閉じます。

* * キャンセル *
+
保存せずにダイアログボックスを閉じます。


