---
permalink: help/reference-new-finder-dialog-box.html 
sidebar: sidebar 
keywords: new, finder, dialog box, enable, create 
summary: '[ 新規ファインダ ] ダイアログボックスでは、新しいファインダを作成できます。' 
---
= 新規 Finder ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 新規ファインダ ] ダイアログボックスでは、新しいファインダを作成できます。

* プロパティタブ
* フィルタ
* [ 戻り属性 ] タブ




== プロパティタブ

「 * プロパティ * 」タブでは、 Finder の名前を指定したり、 WFA ディクショナリオブジェクトのタイプを選択したり、 Finder の概要 を入力したりできます。このタブには、 [ * フィルタ * （ * Filters * ） ] タブでフィルタを選択した後の入力パラメーターも表示されます。

* * 名前 *
+
Finder の名前を入力できます。

* * タイプ *
+
アグリゲート、 igroup 、クラスタなどのオブジェクトタイプをリストから選択できます。選択したオブジェクトのフィルタが * フィルタ * （ * Filters * ）タブに表示されます。

* * エンティティバージョン *
+
Finder のバージョン番号を「 major.minor.revision 」形式で入力できます。たとえば、 1.0.0 です。

* * 概要 *
+
Finder の概要 を入力できます。

* * 入力パラメータ表 *
+
選択したフィルタの入力パラメータを表示します。





== [ フィルタ ] タブ

使用可能なフィルタのリストから必要なフィルタを選択できます。

* * 使用可能なフィルター *
+
選択したオブジェクトで使用可能なフィルタのリストが、 * プロパティ * （ * Properties * ）タブに表示されます。

* * 選択されたフィルタ *
+
使用可能なフィルタから選択したフィルタのリストが表示されます。

* * 選択ボタン *
+
選択したエントリをボックス間で移動します。





== [ 戻り属性 ] タブ

使用可能なフィルタの詳細を確認し、使用可能なフィルタの必要な属性を選択し、属性のソート順序を指定できます。

* * 利用可能 *
+
使用可能なフィルタとフィルタの属性を表示します。

* * 選択済み *
+
選択したフィルタ、属性、エイリアス、および選択したフィルタのソート順序が表示されます。

* * コマンドボタン *
+
** * 上 *
+
選択したエントリを選択したテーブルの 1 行上に移動します。

** * 下 *
+
選択したエントリを選択したテーブルの 1 行下に移動します。

** * 選択ボタン *
+
選択したエントリをテーブル間で移動します。







== コマンドボタン

* * テスト *
+
定義したファインダをテストできます。

* * 保存 *
+
Finder を保存してダイアログボックスを閉じます。

* * キャンセル *
+
は、 Finder を保存せずにダイアログボックスを閉じます。


