---
permalink: help/reference-mvel-enabled-fields-in-wfa.html 
sidebar: sidebar 
keywords: field, oncommand, workflow, automation, enable, expression, language, syntax, design 
summary: OnCommand Workflow Automation \ （ WFA \ ）のいくつかのフィールドは、 MVEL\ （ MVEL\ ）で有効になっています。ワークフローの設計時に、これらのフィールドで MVEL 構文を使用できます。 
---
= OnCommand Workflow Automation の MVEL 対応フィールド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）のいくつかのフィールドは、 MVEL （ MVEL ）で有効になっています。ワークフローの設計時に、これらのフィールドで MVEL 構文を使用できます。

次の表に、 WFA インターフェイスの MVEL 構文を使用できる場合とその場所を示します。

[cols="2*"]
|===
| 状況 | 使用場所 


 a| 
ワークフローの作成または編集
 a| 
* *_Workflow_*>* Details *>* Return Parameters *>* Parameter Value *
* *_Workflow_*>* Details *>* 定数 *>* 値 *




 a| 
ワークフローでコマンドの詳細を作成または編集する
 a| 
* * コマンド * > * parameter_name * > * 検索条件を入力 * > * リソース選択 * > * Finder * > * パラメーター *
* * コマンド * > * Parameters for _parameter_name_*>* 検索条件を入力 * > * リソース選択 * > * 詳細 * > * 次の式が TRUE * と評価された場合のみ、検索を実行します
* * 次の式が TRUE * の場合、 * コマンド * > * パラメータ for _parameter_name_* > * 拡張 * > *
* * コマンド * > * パラメータ for _parameter_name_* > * その他のパラメータ *
* * コマンド * > * _parameter_name_* > * 属性 *




 a| 
コマンドを作成または編集する
 a| 
* * コマンド * > * コマンド定義 _ コマンド _ 名前 _ * > * プロパティ * > * 文字列表現 *




 a| 
関数の作成または編集
 a| 
* * 関数 *>* function_function_name _*>* 関数定義 *




 a| 
テンプレートを作成または編集する
 a| 
* * テンプレート *>* パラメータ for _parameter_name_*>* Template_template_name_*>* 属性 *>* 値 *




 a| 
行の編集
 a| 
* * _ ワークフロー _ * > * ワークフロー * > * リピート行 * > * リピート * > * 回数 *
* *_Workflow_*>* Workflow*>* Repeat row*>* Variables*>* initial_value および expression* の変数
* * ワークフロー * > * ワークフロー * > * 行の繰り返し * > * リピート * > * グループ内のすべてのリソース * > * リソース検索条件 * > * フィルタリングするパラメータ *
* * _ ワークフロー _ * > * ワークフロー * > * 条件の追加 * > * 次の式が TRUE * の場合


|===