---
permalink: help/reference-edit-variable-dialog-box.html 
sidebar: sidebar 
keywords: edit, variable, dialog box, enable, user, input, attributes, workflow 
summary: 変数の編集： <UserInputName> ダイアログボックスでは、ワークフローのユーザー入力属性を編集できます。 
---
= 変数の編集（ Edit Variable ）ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
変数の編集： <UserInputName> ダイアログボックスでは、ワークフローのユーザー入力属性を編集できます。



== プロパティ

* * 変数名 *
+
ユーザ入力の名前を編集できます。ユーザー入力の名前を変更すると、ワークフロー内のユーザー入力に対するすべての参照が更新されます。

* * 表示名 *
+
ユーザ入力の表示名を指定または編集できます。同様の名前でユーザ入力属性を作成した場合は、一意の表示名を指定できます。

* * 概要 *
+
ユーザ入力の概要 を指定または編集できます。ワークフローを実行またはプレビューすると、概要 がツールチップとして表示されます。

* * タイプ *
+
ユーザ入力のタイプを選択できます。選択したオプションに基づいて、フィールドまたはダイアログボックスへのリンクが表示されます。使用できるオプションは次のとおりです。

+
** string ： regex フィールドに有効な値の正規表現を入力できます。たとえば、「 * 」と入力します。
** Number ： Range フィールドに数値範囲を入力できます。たとえば、 1 ～ 15 のように入力できます。
** Enum ： [Enum Values] フィールドに、値の閉じたリストを入力できます。
** Query ：単純な SQL クエリを入力して結果を取得できます。
+
ユーザーは、結果の最初の列から値のみを選択できます。

** クエリ（複数選択）：値のリストを取得する SQL クエリを入力できます。
+
ワークフローの実行中に単一の値または複数の値を選択できます。たとえば、単一のボリューム、複数のボリューム、または共有とエクスポートが設定されたボリュームを選択できます。

+
結果に表示された任意の列から値を選択できます。行を選択すると、選択した行のすべての列から値が選択されます。

** ブール： [ ユーザー入力（ User Inputs ） ] ダイアログボックスにチェックボックスを表示できます。
** 表：ワークフローの実行中に複数の値を入力できるテーブルの列ヘッダーを指定できます。たとえば、ノード名とポート名のリストを指定するテーブルなどです。
+
列ユーザー入力のタイプと、列ユーザー入力に関連付けられたプロパティを構成することもできます。選択したユーザ入力タイプに基づいてダイアログボックスが表示されます。使用できるオプションは次のとおりです。

+
*** string ： regex フィールドに有効な値の正規表現を入力できます。たとえば、「 * 」と入力します。
*** Number ： Range フィールドに数値範囲を入力できます。たとえば、 1 ～ 15 のように入力できます。
*** Enum ： [Enum Values] フィールドに、値の閉じたリストを入力できます。
*** Query ：単純な SQL クエリを入力して結果を取得できます。
+
ユーザーは、結果の最初の列から値のみを選択できます。テーブルユーザ入力の列内のクエリは、クエリ内の他のユーザ入力を参照できません。

*** Boolean ：ドロップダウンリストからブール値として「 true 」または「 false 」を選択できます。


** Password ：ユーザに入力として提供されるパスワードを暗号化できます。
+
暗号化されている場合、 WFA アプリケーションとログファイルに一連のアスタリスク文字が表示されます。

** 辞書：選択した辞書エントリのテーブルデータを追加できます。
+
辞書エントリ属性は、返される属性を選択します。ワークフローの実行中に、単一の値または複数の値を選択できます。たとえば、単一のボリューム、複数のボリューム、または共有とエクスポートが設定されているボリュームを選択できます。デフォルトでは、単一の値が選択されています。フィルタ処理のルールを選択することもできます。ルールは、ディクショナリエントリ属性、演算子、および値で構成されます。属性には、その参照の属性も含めることができます。たとえば、文字列「 aggr 」で始まる名前のすべてのアグリゲートを一覧表示し、使用可能なサイズが 5GB を超えるアグリゲートのルールを指定できます。グループの最初の規則は ' 属性名 ' 演算子 'starts-name' と値 kaggr です同じグループの 2 番目の規則は ' 属性 available_size_mb' で ' 演算子は '>' および値は 5000 です



* * ロック値 *
+
クエリから返された値以外の値の入力をユーザに許可するかどうかを指定できます。このチェックボックスをオンにすると、ユーザは値を指定できません。選択できるのは、クエリーから返された値のみです。このオプションは、 Enum および Query type オプションとともに使用します。

* * デフォルト値 *
+
ユーザ入力のデフォルト値を設定できます。

* * 必須 *
+
ワークフローの実行にユーザ入力が必須かどうかを指定できます。





== グループ

* * グループ名 *
+
関連するユーザ入力属性をグループ化できます。ユーザー入力属性は、ワークフローのプレビューまたは実行時に定義したグループに表示されます。たとえば、ボリュームの詳細に関連するユーザ入力属性をグループ化できます。

* * デフォルトでグループを展開 *
+
グループに指定されているすべてのユーザ入力属性を展開リストとして表示できます。このチェックボックスをオフにすると、ユーザー入力グループが折りたたまれて表示されます。





== 依存関係

別のユーザ入力用に入力した値に基づいてユーザ入力を有効にできます。たとえば 'NAS プロトコルを構成するワークフローでは ' 読み取り / 書き込みホスト・リスト "" ユーザー入力 "" または CIFS ACL 設定 "" を有効にするために ' プロトコルに必要なユーザー入力を "NFS" として指定できます

* * 依存するユーザー入力を選択します *
+
変数名フィールドに表示されるユーザー入力を有効にするために必要なユーザー入力を選択できます。

* * 適用可能な値（カンマ区切り） *
+
変数名フィールドに表示されるユーザ入力を有効にする条件付きユーザ入力の値を指定できます。


