---
permalink: help/reference-new-remote-system-type-dialog-box.html 
sidebar: sidebar 
keywords: new, remote, system, type, dialog box, enable, add, oncommand, workflow, automation, predefined, meet, requirement, change, configuration 
summary: 新しいリモートシステムタイプダイアログボックスでは、事前定義されたシステムタイプが要件に合わない場合や、事前定義されたシステムタイプの設定を変更する場合に、新しいリモートシステムタイプを OnCommand Workflow Automation （ WFA ）に追加できます。 
---
= [ 新しいリモートシステムタイプ ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいリモートシステムタイプダイアログボックスでは、事前定義されたシステムタイプが要件に合わない場合や、事前定義されたシステムタイプの設定を変更する場合に、新しいリモートシステムタイプを OnCommand Workflow Automation （ WFA ）に追加できます。

* [ 詳細 ] タブ
* [ 検証スクリプト ] タブ




== [ 詳細 ] タブ

名前、概要 、バージョン、接続プロトコルなど、リモートシステムの種類の詳細を指定できます。

* * 名前 *
+
リモートシステムの種類の名前を指定できます。リモートシステムタイプを保存するには、名前を指定する必要があります。

* * 概要 *
+
リモートシステムタイプの概要 を入力できます。

* * バージョン *
+
リモート・システム・タイプのバージョン番号を 'major.minor.revision 形式で指定できますたとえば '1.0.0 です

* * 接続プロトコル *
+
リモートシステムに接続する際に WFA で使用する次のプロトコルのいずれかを選択できます。

+
** HTTPS を HTTP にフォールバックします
+
接続では主に HTTPS が使用されます。HTTPS 経由の接続に失敗した場合は、 HTTP が使用されます。HTTP 経由の接続にも失敗した場合、接続試行は破棄されます。

** HTTPS のみ
** HTTP のみ
** カスタム




接続プロトコルを選択すると、プロトコル、デフォルトポート、およびデフォルトタイムアウト（秒）フィールドにデータが入力されます。



== [ 検証スクリプト ] タブ

選択したプロトコルとリモートシステムタイプの接続をテストできます。

接続をテストするスクリプトを実行するには、 * Perl スクリプトのテスト * をクリックします。



== コマンドボタン

* * 保存 *
+
リモートシステムタイプの設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


