---
permalink: help/reference-new-active-directory-group-dialog-box.html 
sidebar: sidebar 
keywords: active, directory, group, enable, create, new, oncommand, workflow, automation 
summary: '[ 新しい Active Directory グループ ] ダイアログボックスでは、新しい OnCommand Workflow Automation Active Directory グループを作成できます。' 
---
= [ 新しい Active Directory グループ ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 新しい Active Directory グループ ] ダイアログボックスでは、新しい OnCommand Workflow Automation Active Directory グループを作成できます。

* * グループ名 *
+
グループ名を指定します。

* * 役割 *
+
次のいずれかのグループロールを選択できます。

+
** * ゲスト *
+
このグループは、ワークフロー実行のステータスのみを表示したり、ワークフロー実行のステータスの変更について通知したりすることができます。

** * 演算子 *
+
このグループには、グループにアクセス権が付与されているワークフローをプレビューして実行することができます。

** * 承認者 *
+
このグループでは、グループにアクセス権が付与されているワークフローをプレビュー、実行、承認、および拒否できます。

+

NOTE: 承認者の E メール ID と、承認者に通知するワークフローのステータスを入力する必要があります。複数の承認者がいる場合は、 [ 電子メール *] フィールドにグループ電子メール ID を入力できます。

** * 建築家 *
+
このグループには作成ワークフローへのフルアクセスがありますが、 WFA サーバのグローバル設定の変更は制限されます。

** * 管理者 *
+
このグループは WFA サーバへの完全なアクセス権を持っています。

+

NOTE: 管理者グループを少なくとも 1 つ設定する必要があります。



* * 電子メール *
+
通知を送信するグループの E メールアドレスを指定できます。このアドレスには、 * 通知オン * オプションが選択されています。

* * 通知オン *
+
Active Directory グループに E メールで通知するタイミングを選択できます。ワークフローの実行ステータス通知は、グループによって実行されたワークフローに固有のものです。次のオプションを任意に組み合わせて選択できます。

+
** ワークフローの実行が開始されました : ワークフローの実行が開始されたときにグループに通知します
** ワークフローの実行に失敗した / 部分的に成功した：ワークフローの実行に失敗した場合、または 1 つ以上のステップが失敗した場合でもワークフローが正常に実行された場合に、グループに通知します。
+
失敗したステップが、そのステップが失敗してもワークフローを続行できるように設定されているため、実行は完了しました。

** ワークフローの実行が正常に完了しました：ワークフローの実行が正常に完了したことをグループに通知します。
** 承認待ちのワークフローの実行： WFA の設定に応じて、ワークフローの実行が承認待ちの状態にある場合に、グループに通知します。承認待ちのグループには、 Approver 、 Architect 、または Operator からの承認が必要です。






== コマンドボタン

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


