---
permalink: help/reference-resource-selection-dialog-box.html 
sidebar: sidebar 
keywords: resource, selection, dialog box, enable, search, map, command 
summary: '[ リソースを選択（ Resource Selection ） ] ダイアログボックスでは、リソースを検索してコマンドにマッピングできます。' 
---
= [ リソースを選択（ Resource Selection ） ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ リソースを選択（ Resource Selection ） ] ダイアログボックスでは、リソースを検索してコマンドにマッピングできます。

* <dictionary object> By タブを選択します
* [ 詳細設定 ] タブ




== <dictionary object> By タブを選択します

このタブでは、検索条件としてファインダまたはフィルタを指定し、選択した検索条件の属性を入力できます。選択したフィルタを Finder として保存することもできます。

* * フィルタルールを定義 *
+
vFiler ユニット、アグリゲート、仮想マシンなど、ディクショナリエントリリソース用のルールセットを定義できます。

+
フィルタルールには、 1 つ以上のルールグループを含めることができます。

+
ルールは、ディクショナリエントリ属性、演算子、および値で構成されます。属性には、その参照の属性も含めることができます。たとえば、次のようにアグリゲートのルールを指定できます。 List all aggregates with name starting with the string "aggr>" and have an available size greater than 5GB .グループの最初のルールは属性 "`name`" で、演算子 "`starts-name", および値 "aggr`") です。同じグループの 2 番目の規則は ' 属性 "available_size_MB`") で ' 演算子は "`>` で ' 値は "5000`" です

+
Finder を選択した場合は、「 * フィルタルールを定義する * 」オプションが無効になります。

+
指定した値をクリアするには、 * リセット * ボタンをクリックします。

* * 自然キーで 1 つのリソースを選択 *
+
リソースの自然キーに基づいてリソースを選択できます。

* * Finder *
+
リストから Finder を選択できます。* なし * がデフォルトで選択されています。

+
フィルタは Finder リストの下に表示されます。Finder を選択した場合は、フィルタを選択できません。

* * パラメータ *
+
選択したファインダまたはフィルタの値を入力できます。検索条件を満たすために必要なすべての値を入力する必要があります。

* * コマンドボタン *
+
** * Finder として保存 *
+
選択したフィルタを Finder として保存します。

** * テスト *
+
パラメーター（ Parameters ）領域で値を指定する前に、選択したフィルタのパラメーターをテストできます。

** * OK *
+
設定を保存してダイアログボックスを閉じます。

** * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。







== [ 詳細設定 ] タブ

このタブでは、検索を実行するタイミングを指定したり、リソース属性とリソース属性のステータスをソートしたりできます。

* * この検索は常に実行してください *
+
コマンドの実行時に制限なしで検索を実行します。

* * 次の式が TRUE * と評価された場合のみ、検索を実行します
+
ボックスで指定されたオプション属性の値が「真」の場合にのみ、検索を実行します。オプションの属性を指定するには、 MVEL （ MVEL ）構文を使用します。

* * ソートテーブル *
+
*Select < 辞書オブジェクト > By * タブで選択したフィルターの属性と並べ替え順序を表示します。ソート順序は、リソースの選択にとって重要です。たとえば、アグリゲートのソート順序として descending を選択した場合、最大「 available_space 」のアグリゲートがリソースとして選択されます。属性のソート順序を変更するには、属性のステータス列をクリックし、リストから必要なソート順序を選択します。

* * コマンドボタン *
+
** * 上 *
+
選択したエントリをソートテーブルの 1 行上に移動します。

** * 下 *
+
選択したエントリをソートテーブルの 1 行下に移動します。




