---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: '[New Credentials] ダイアログボックスでは、新しいクレデンシャルを作成できます。' 
---
= [ 新しい資格情報 ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[New Credentials] ダイアログボックスでは、新しいクレデンシャルを作成できます。



== クレデンシャルパラメータ

新しく作成されたクレデンシャルには、次のパラメータを設定できます。

* * マッチ *
+
クレデンシャルの一致タイプを選択できます。これにより、特定の IP アドレスまたはホスト名のクレデンシャル、またはサブネット全体または IP 範囲のクレデンシャルが定義されます。次のいずれかのオプションを選択できます。

+
** Exact ：特定の IP またはホスト名の資格情報を定義します
** pattern ：ホスト名の範囲またはサブネット全体または IP 範囲のクレデンシャルを定義します
+
pattern は、文字列の照合に使用される正規表現です。たとえば '10.10.10.' は 10.10.10.0 ～ 10.10.10.255 の範囲の任意の IP に一致し 'host' は 'host' で始まるすべてのホスト名に一致します



* * タイプ *
+
ドロップダウンリストからホストタイプを選択できます。

+

NOTE: VMware vCenter は Linux ではサポートされていません。

* * 名前 /IP *
+
クレデンシャルのホスト名または IP アドレスを指定できます。

* * ユーザー名 *
+
クレデンシャルのユーザ名を指定できます。

* * パスワード *
+
クレデンシャルに対して作成したユーザ名のパスワードを指定できます。

* * デフォルト値を上書き *
+
クレデンシャルについて選択したリモートシステムタイプに関連付けられているプロトコル、ポート、およびタイムアウトのデフォルト値を上書きできます。

+
デフォルトでは、このチェックボックスは選択されていません。デフォルト値を上書きする場合は、チェックボックスを選択する必要があります。





== コマンドボタン

* * テスト *
+
必要なクレデンシャルを使用してログインすることで、ホストまたは IP アドレスへの接続をテストできます。

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


