---
permalink: help/reference-new-user-dialog-box.html 
sidebar: sidebar 
keywords: new, user, dialog box, enable, create, account 
summary: '[ 新しいユーザー ] ダイアログボックスでは、新しいユーザーアカウントを作成できます。' 
---
= New User ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 新しいユーザー ] ダイアログボックスでは、新しいユーザーアカウントを作成できます。

* * ユーザー名 *
+
ユーザ名を指定します。

* * 役割 *
+
次のいずれかのユーザロールを選択できます。

+
** ゲスト : このユーザーは、ワークフロー実行のステータスのみを表示したり、ワークフロー実行のステータスの変更を通知したりすることができます。
** Operator ：ユーザにアクセス権が付与されたワークフローをプレビューおよび実行できます。
** Architect ：このユーザには作成ワークフローへのフルアクセスが許可されていますが、 WFA サーバのグローバル設定の変更は禁止されています。
** admin ：このユーザには WFA サーバへの完全なアクセス権があります。
** Backup ： WFA サーバのバックアップをリモートで生成できる唯一のユーザです。ただし、他のすべてのアクセスは制限されます。


* * 電子メール *
+
通知オンオプションが選択されている場合に通知を送信するユーザーの電子メールアドレスを指定できます。

* * パスワード *
+
ユーザのパスワードを指定します。

* * 確認 *
+
パスワードをもう一度指定します。

* * 通知オン *
+
アカウントユーザに E メールで通知するタイミングを選択できます。ワークフローの実行ステータスの通知は、ユーザが実行したワークフローに固有のものです。次のオプションを任意に組み合わせて選択できます。

+
** ワークフローの実行が開始されました : ワークフローの実行が開始されたときにユーザーに通知します
** ワークフローの実行に失敗した / 部分的に成功した場合：ワークフローの実行に失敗した場合、または 1 つ以上のステップが失敗した場合でもワークフローが正常に実行された場合に、ユーザーに通知します。
+
実行は、失敗したステップが、ステップが失敗してもワークフローの実行が継続するように構成されているために完了します。

** ワークフローの実行が正常に完了しました：ワークフローの実行が正常に完了したことをユーザに通知します。
** 承認待ちのワークフローの実行： WFA の設定によっては、 Operator ユーザまたは Architect ユーザからの承認を待っているワークフローが実行された場合にユーザに通知します。
** データ収集の失敗：データソースのデータ収集が失敗したときにユーザに通知します。
+
このオプションは、管理者ユーザとアーキテクトユーザに対してのみ有効になります。







== コマンドボタン

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


