---
permalink: help/reference-mvel-enabled-fields-in-wfa.html 
sidebar: sidebar 
keywords: field, oncommand, workflow, automation, enable, expression, language, syntax, design 
summary: OnCommand Workflow Automation （ WFA ）のいくつかのフィールドは、 MVEL （ MVEL ）で有効になっています。ワークフローの設計時に、これらのフィールドで MVEL 構文を使用できます。 
---
= OnCommand Workflow Automation の MVEL 対応フィールド
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）のいくつかのフィールドは、 MVEL （ MVEL ）で有効になっています。ワークフローの設計時に、これらのフィールドで MVEL 構文を使用できます。

次の表に、 WFA インターフェイスの MVEL 構文を使用できる場合とその場所を示します。

[cols="2*"]
|===
| 状況 | 使用場所 


 a| 
ワークフローの作成または編集
 a| 
* _MENU：ワークフロー_[詳細>戻りパラメータ>パラメータ値]
* _MENU:ワークフロー_[詳細>定数>値]




 a| 
ワークフローでコマンドの詳細を作成または編集する
 a| 
* メニュー：コマンド[Parameters for _parameter_name_>Enter search criteria > Resource Selection > Finder > Parameters ]
* メニュー:コマンド[Parameters for _parameter_name_>Enter search criteria > Resource Selection > Advanced > Execute search only when the following expression evaluates to true]
* メニュー:コマンド[Parameters for _parameter_name_>Advanced> if the following expression is true]
* メニュー：コマンド[Parameters for _parameter_name_> Other Parameters]
* メニュー:コマンド[_parameter_name_>Attributes]




 a| 
コマンドを作成または編集する
 a| 
* メニュー：コマンド[コマンド定義_コマンド_名前_>プロパティ>文字列表現]




 a| 
関数の作成または編集
 a| 
* メニュー:関数[FUNCTION_FUNCTION_NAME_>関数定義]




 a| 
テンプレートを作成または編集する
 a| 
* メニュー:テンプレート[パラメータfor _parameter_name_>Template_template_name_>属性>値]




 a| 
行の編集
 a| 
* メニュー:ワークフロー_[ワークフロー>行の繰り返し>繰り返し回数]
* メニュー:ワークフロー_[ワークフロー>行の繰り返し>変数>_initial_value_or_expression_の変数]
* メニュー:ワークフロー_[ワークフロー>行の繰り返し>繰り返し>グループ内のすべてのリソース>リソース検索条件>フィルタするパラメータ]
* _MENU:ワークフロー_[ワークフロー>条件の追加>次の式がTRUEの場合]


|===