---
permalink: help/reference-edit-data-source-dialog-box.html 
sidebar: sidebar 
keywords: edit, data, source, dialog box, enable, modify, existing 
summary: Edit Data Source ダイアログボックスでは、既存のデータソースを変更できます。 
---
= [ データソースの編集 ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Edit Data Source ダイアログボックスでは、既存のデータソースを変更できます。



== データソース構成のプロパティ

* * 名前 *
+
データソースの名前を変更できます。

* * データソースの種類 *
+
データソースのデータソースタイプが表示されます。このフィールドは変更できません。

* * ホスト名 *
+
データソースのホスト名または IP アドレス（ IPv4 または IPv6 ）を指定できます。

+

NOTE: Active IQ Unified Manager データソースタイプでは、 IPv6 アドレスはサポートされません。

* * ポート *
+
選択したデータソースタイプに関連付けられているポート番号（ある場合）が表示されます。データソースのデフォルトのポート番号は変更できます。

* * スキーム *
+
選択したデータソースのタイプに関連付けられているスキームが表示されます。例： _cm_storage_for Unified Manager - 6.0 （ MySQL ）。

+
このプロパティは変更できません。

* * ユーザー名 *
+
選択したデータソースタイプに関連付けられているユーザ名（存在する場合）が表示されます。

+
デフォルトのユーザ名を上書きするには、このデータソースに適切なユーザ名を指定する必要があります。

+
** Unified Manager 6.0 以降では、 Unified Manager サーバで作成したデータベースユーザアカウントのユーザ名を入力する必要があります。
** Performance Advisor の場合は、 GlobalRead の最小ロールを持つ Active IQ Unified Manager ユーザのユーザ名を入力する必要があります。


* * パスワード *
+
選択したデータソースのタイプに対応するパスワードを指定できます。

+
このデータソースのユーザ名のデフォルトのパスワードを上書きするには、パスワードを指定する必要があります。

+
** Unified Manager 6.0 以降では、サーバで作成したデータベースユーザアカウントのパスワードを入力する必要があります。
** Performance Advisor の場合、 GlobalRead の最小ロールを持つ Unified Manager ユーザのパスワードを入力する必要があります。


* * データベース *
+
選択したデータソースタイプに関連付けられているデータベース名（存在する場合）が表示されます。

* * 間隔（分） *
+
値をクリックし、上下の矢印を使用して間隔（分）を選択できます。

+

NOTE: 間隔をゼロ（ 0 ）に設定すると、自動サンプリングは無効になります。

+
データサンプリングのデフォルトの間隔は次のとおりです。

+
** スクリプトベースのデータソースの種類： 1440 （パフォーマンスと VC ）
** SQL ベースのデータソースのタイプ： 30 （ cm_storage 、 storage 、 cm_performance ）


* * セットアップ手順ガイド * を参照してください
+
データソースを設定する手順の概要を示すセットアップ手順ガイド（ Setup Instruction Guide ）ダイアログボックスを開きます。





== コマンドボタン

* * スキームのリセット *
+
スキームのリセットの確認ダイアログボックスを開きます。このダイアログボックスでは、選択したスキームのキャッシュストレージをリセットできます。これは次回のデータ取得時に発生します。

+

IMPORTANT: リセット処理では、すべてのテーブルを含むキャッシュされたデータがすべて削除されます。キャッシュ全体は、次回のデータ取得時に最初から作成されます。

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


