---
permalink: help/reference-clone-finder-dialog-box.html 
sidebar: sidebar 
keywords: clone, finder, dialog box, enable, create, copy, finder, edit 
summary: '[ クローンファインダ ] ダイアログボックスでは、ファインダのコピーを作成し、クローン作成されたファインダを編集できます。' 
---
= [ クローンファインダ ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ クローンファインダ ] ダイアログボックスでは、ファインダのコピーを作成し、クローン作成されたファインダを編集できます。

* プロパティタブ
* フィルタ
* [ 戻り属性 ] タブ




== プロパティタブ

[ プロパティ ] タブでは、 Finder の名前、オブジェクトのタイプ、および Finder の概要 を編集できます。このタブには、 Finder で使用されるフィルタの入力パラメータも表示されます。

* * 名前 *
+
Finder の名前を編集できます。クローンを作成するために選択したファインダの名前が ' クローンの名前として使用され ' デフォルトでは '-copy' が付加されます

* * タイプ *
+
リストからオブジェクトのタイプを選択できます。選択したオブジェクトのフィルタが [ フィルタ（ Filters ） ] タブに表示されます。

* * エンティティバージョン *
+
Finder のバージョン番号を「 major.minor.revision 」形式で入力できます。たとえば、 1.0.0 です。

* * 概要 *
+
Finder の概要 を編集できます。

* * 入力パラメータ表 *
+
選択したフィルタの入力パラメータを表示します。





== [ フィルタ ] タブ

使用可能なフィルタのリストから必要なフィルタを選択できます。

* * 使用可能なフィルター *
+
[ プロパティ（ Properties ） ] タブに、選択したオブジェクトで使用可能なフィルタのリストが表示されます。

* * 選択されたフィルタ *
+
使用可能なフィルタから選択したフィルタのリストが表示されます。

* * 選択ボタン *
+
選択したエントリを別のボックスに移動できます。





== [ 戻り属性 ] タブ

使用可能なフィルタの詳細を確認し、使用可能なフィルタの必要な属性を選択し、属性のソート順序を指定できます。

* * 利用可能 *
+
使用可能なフィルタとフィルタの属性を表示します。

* * 選択済み *
+
選択したフィルタ、属性、エイリアス、および選択したフィルタのソート順序が表示されます。

* * コマンドボタン *
+
** * 上 *
+
選択したエントリを選択したテーブルの 1 行上に移動します。

** * 下 *
+
選択したエントリを選択したテーブルの 1 行下に移動します。

** * 選択ボタン *
+
選択したエントリをテーブル間で移動します。







== コマンドボタン

* * テスト *
+
クローンを作成するために選択したファインダをテストできます。

* * 保存 *
+
Finder を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


