---
permalink: help/reference-edit-user-dialog-box.html 
sidebar: sidebar 
keywords: edit, user, dialog box, enable, view, modify, account, settings 
summary: ユーザーの編集ダイアログボックスでは、ユーザーアカウントの設定を表示および変更できます。 
---
= Edit User ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザーの編集ダイアログボックスでは、ユーザーアカウントの設定を表示および変更できます。

アカウントの権限とロールによっては、「ユーザ」ウィンドウにアクセスできない場合があります。ただし、「 * 設定 * 」を選択し、「 * 管理 * 」で「 * アカウント設定 * 」をクリックして、アカウントの設定を編集することができます。


NOTE: 編集可能なフィールドは、割り当てられているロールとアカウントの権限によって異なります。

* * 名前 *
+
ユーザアカウントのユーザ名が表示されます。

* * 役割 *
+
ユーザアカウントに割り当てられているロールが表示されます。

* * 電子メール *
+
Notify On （通知オン）オプションが選択されている場合に通知が送信されるユーザーアカウントの電子メールを指定します。

* * パスワードの変更 *
+
ユーザアカウントの現在のパスワードを変更できます。このチェックボックスをオンにすると、次のフィールドが必要になります。

+
** * 新しいパスワード * -- 新しいパスワードを指定します
** * Confirm * -- 新しいパスワードをもう一度指定します。


* * 通知オン *
+
ワークフローの実行中にアカウントユーザに E メールで通知するタイミングを選択できます。このチェックボックスをオンにすると、次のオプションを任意に組み合わせて選択できます。

+
** ワークフローの実行が開始されました : ワークフローの実行が開始されたときにユーザーに通知します
** ワークフローの実行に失敗した / 部分的に成功した場合：ワークフローの実行に失敗した場合、または 1 つ以上のステップが失敗した場合でもワークフローが正常に実行された場合に、ユーザーに通知します。
+
実行は、失敗したステップが、ステップが失敗してもワークフローの実行が継続するように構成されているために完了します。

** ワークフローの実行が正常に完了しました：ワークフローの実行が正常に完了したことをユーザに通知します。
** 承認待ちのワークフローの実行： WFA の設定によっては、 Operator ユーザまたは Architect ユーザからの承認を待っているワークフローが実行された場合にユーザに通知します。
** データ収集の失敗：データソースのデータ収集が失敗したときにユーザに通知します。
+
このオプションは、管理者ユーザとアーキテクトユーザに対してのみ有効になります。







== コマンドボタン

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


