---
permalink: help/reference-edit-workflow-window.html 
sidebar: sidebar 
keywords: workflow, window, display, select, associated, commands, parameters, blue boxes, columns, arranged, sequential, order, execution, left, right, variables, objects, gray boxes 
summary: '[ ワークフロー < ワークフロー名 >] ウィンドウには、選択したワークフローとその関連コマンドおよびパラメータが表示されます。ワークフローに関連するコマンドは、列に青のボックスとして表示され、列は実行の順番に左から右に並べられます。各コマンドの変数とオブジェクトは、コマンドの下にグレーのボックスで表示されます。' 
---
= Workflow < ワークフロー名 > ウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ ワークフロー < ワークフロー名 >] ウィンドウには、選択したワークフローとその関連コマンドおよびパラメータが表示されます。ワークフローに関連するコマンドは、列に青のボックスとして表示され、列は実行の順番 ( 左から右 ) で並べられます。各コマンドの変数とオブジェクトは、コマンドの下にグレーのボックスで表示されます。



== [ ワークフロー ] タブ

[ ワークフロー ] タブでは、子ワークフローとコマンドを選択して使用し、表示名をカスタマイズできます。

* * 利用可能なステップ *
+
ワークフローに追加できる、使用可能な子ワークフローとコマンドのリストが表示されます。

+
テキストボックスで検索文字列として名前、スキーム、および最小ソフトウェアバージョンを使用することで、子ワークフローまたはコマンドを検索できます。

+
コマンドの順序を並べ替えることで、ワークフローの表示をカスタマイズできます。コマンドを並べ替えるには、コマンドを必要な順序でドラッグアンドドロップします。コマンドをダブルクリックすると、そのコマンドがリストの末尾に移動します。青のボックス内のコマンドの表示名をダブルクリックすると、表示名を変更できます。コマンドを削除するには ' カーソルを青いボックスの上に移動し ' 右上隅の [X] をクリックします

+
行番号をクリックすると、その行に対してさまざまな機能を実行できます。

+
** * 行を挿入 *
+
ワークフローで選択した行の上または下に新しい行を挿入します。

** * 行をコピー *
+
選択した行をワークフローからコピーしてクリップボードに保存します。行の繰り返しの詳細セットは、行がコピーされるときにコピーされます。

** * 行の繰り返し *
+
[ 行の繰り返しの詳細 ] ダイアログボックスを開きます。このダイアログボックスで、繰り返しの種類を指定できます。

** * 条件の追加 *
+
行 < 行番号 > の条件ダイアログボックスが開き、条件を選択できます。選択した条件は、行のすべてのコマンドに適用されます。選択した条件が満たされた場合にのみ、行のすべてのコマンドが実行されます。

** * 行を削除 *
+
選択した行をワークフローから削除します。



* * 行を貼り付け *
+
選択した行の上または下にコピーした行を貼り付けます。このオプションは、 [ 行をコピー（ Copy row ） ] 機能を選択した後で使用できます





== [ 詳細 ] タブ

[ 詳細 ] タブでは、ワークフローに関する一般的な情報を指定できます。

* * ワークフロー名 *
+
英数字の文字列を使用してワークフローの名前を指定できます。

* * エンティティバージョン *
+
ワークフローのバージョン番号を 'major.minor.revision 形式で入力できますたとえば '1.0.0 です

* * カテゴリ *
+
ワークフローの関連カテゴリが表示されます。[ カテゴリ ] ウィンドウからワークフローをカテゴリに割り当てることができます。

* * ワークフロー概要 *
+
ワークフローの概要 を入力できます。フィールド内をクリックすると、 [ 編集（ Edit ） ] [ 編集（概要 ） ] ダイアログボックスが開きます。

* * 生産準備完了 *
+
ワークフローを本番用に準備しておくことができますこれにより ' ワークフローを実行して [ ワークフロー ] ウィンドウに一覧表示することができます

* * 予約された要素 * を考慮しなさい
+
ワークフローで選択したリソースが使用可能になっている場合に、設定したリザベーションの有効期限まで、ワークフローでリザベーション機能を使用できます。リザベーション機能を使用すると、リソースの選択時に他のワークフローで予約されているリソースを除外できます。

+

NOTE: 他のワークフローで設定された予約を考慮せずに永続キャッシュのコンテンツのみを検索するフィルタが必要な場合は、このチェックボックスをオンにしないでください。

* * 要素の存在検証を有効にします *
+
エレメントの存在を検証し、ワークフローの実行中に特定のアクションの失敗を回避できます。たとえば、既存のボリュームと同じ名前の新しいボリュームをアレイに作成することは避けてください。

* * 最小ソフトウェアバージョン *
+
ワークフローを実行するために必要なソフトウェアの最小バージョンを指定します。たとえば、 clustered Data ONTAP 8.2.0 と vCenter 6.0 を使用できます。各バージョンがカンマで区切って表示されます。





== [ ユーザー入力 ] タブ

[ ユーザー入力（ User Inputs ） ] タブでは、ワークフローオブジェクトを定義し、ユーザー入力を作成したときに作成したユーザー入力属性を表示および編集できます。ワークフローをプレビューまたは実行すると、ユーザー入力属性の値が入力されます。

編集するユーザー入力をダブルクリックすると、 [ 変数の編集： < ユーザー入力 > （ Edit Variable ： <user_input> ） ] ダイアログボックスが開き、ユーザー入力を編集できます。

列の順序を並べ替えることで、テーブルの表示をカスタマイズできます。列を並べ替えるには、列を必要な順序でドラッグアンドドロップします。ただし、これらの列を非表示にしたり削除したりすることはできません。

* * 名前 *
+
ユーザ入力属性の名前を表示します。

* * 表示名 *
+
ワークフローユーザに表示される名前が表示されます。

* * タイプ *
+
文字列、クエリ、ブーリアン、テーブルなどのユーザ入力タイプを表示します。 または password 。

* * 値 *
+
ユーザ入力に使用できる値を表示します。たとえば、数値の範囲や文字列の正規表現などです。

* * デフォルト値 *
+
ユーザ入力のデフォルト値が表示されます。

* * 入力依存関係 *
+
選択したユーザー入力に値を提供する、リストからの別のユーザー入力を表示します。

* * グループ *
+
ユーザ入力属性のグループの名前が表示されます。

* * 必須 *
+
ユーザ入力のステータスが表示されます。このチェックボックスがオンになっている場合、ワークフローの実行にはユーザ入力属性が必須です。

* * コマンドボタン *
+
** * 上 *
+
選択したエントリをテーブル内の 1 行上に移動します。

** * 下 *
+
選択したエントリをテーブル内の 1 行下に移動します。







== [ 定数 ] タブ

[ 定数 ] タブでは、ワークフローで複数回使用できる定数の値を定義できます。定数の値として、次の項目を指定できます。

* 数字
* 文字列
* MVEL 式
* 機能
* ユーザ入力
* 変数（ variables ）


各列をソートしたり、列の順序を並べ替えたりして、テーブルの表示をカスタマイズできます。

* * 名前 *
+
定数の名前を表示します。

* * 概要 *
+
定数の概要 を指定できます。

* * 値 *
+
定数の値を指定できます。

* * コマンドボタン *
+
** * 追加 * 。
+
定数 (Constants) テーブルに新しい行を追加します

** * 削除 *
+
選択した行を定数 (Constants) テーブルから削除します



+
定数を右クリックして、コピー & ペースト機能を使用することもできます。





== [ 戻りパラメータ ] タブ

Return Parameters タブでは、 Monitoring ウィンドウまたは Web サービスから表示できるワークフローの戻りパラメータの概要 を定義および提供できます。

* * パラメータ値 *
+
パラメータ値を指定できます。

* * パラメータ名 *
+
パラメータ名を指定できます。

* * 概要 *
+
選択したパラメータの概要 を指定できます。

* * コマンドボタン *
+
** * 行を追加 *
+
Return Parameters テーブルに新しい行を追加します。

** * 行の削除 *
+
選択した行を Return Parameters テーブルから削除します。







== ヘルプコンテンツタブ

[ ヘルプコンテンツ ] タブでは、ワークフローのヘルプコンテンツを追加、表示、および削除できます。ワークフローヘルプの内容は、ストレージオペレータ向けのワークフローに関する情報を提供します。



== [ 詳細設定 ] タブ

Advanced タブでは、 API 呼び出しを使用したワークフローの実行用にカスタム URI パスを設定できます。URI パス内の各セグメントには、文字列またはかっこ内のワークフローのユーザ入力の有効な名前を使用できます。

たとえば、 /DevOps / ｛ ProjectName ｝ / clone のように指定します。ワークフローは、 _https ： // wfa -Server ： HTTPS_PORT_rest/DevOps / Project1/clone/jobs の呼び出しとして呼び出すことができます。



== コマンドボタン

コマンドボタンは、ワークフローウィンドウの下部にあります。コマンドには、ウィンドウの右クリックメニューからもアクセスできます。

* * プレビュー *
+
[ ワークフローのプレビュー ] ダイアログボックスが開き、ユーザー入力属性を指定できます。

* * 名前を付けて保存 *
+
ワークフローを新しい名前で保存できます。

* * 保存 *
+
構成設定を保存します。


