---
permalink: help/reference-clone-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: clone, command, definition, dialog box, enable, copy, edit 
summary: '[ コマンド定義を複製（ Clone Command Definition ） ] ダイアログボックスでは、コマンドをコピーして、複製されたコマンドを編集できます。' 
---
= [ クローンコマンド定義（ Clone Command Definition ） ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ コマンド定義を複製（ Clone Command Definition ） ] ダイアログボックスでは、コマンドをコピーして、複製されたコマンドを編集できます。

* プロパティタブ
* [ コード ] タブ
* [ パラメーターを定義（ Parameters Definition ）
* [ パラメータマッピング（ Parameters Mapping ） ] タブ
* [ 予約 ] タブ
* [Verification （検証） ] タブ




== プロパティタブ

クローニングしたコマンドの名前、概要 、エンティティバージョンなどのプロパティを編集できます。

* * 名前 *
+
クローニングしたコマンドの名前を編集できます。デフォルトでは、クローン作成用に選択したコマンドの名前が、「 -copy 」を追加したクローンの名前として使用されます。

* * エンティティバージョン *
+
コマンドのバージョン番号を「 major.minor.revision 」形式で編集できます。たとえば、 1.0.0 です。

* * 概要 *
+
コマンドの概要 を編集できます。

* * 文字列表現 *
+
MVFLEX Expression Language （ MVEL ）構文を使用して、コマンドの文字列表現を指定できます。コマンドを保存するには、文字列表現を指定する必要があります。

* * タイムアウト *
+
コマンドのタイムアウト値（秒）を指定できます。デフォルト値は 600 秒です。

* * コマンドタイプ *
+
コマンドの実行タイプを指定できます。

+
** * 標準実行 *
+
待機時間を指定せずにコマンドを実行できるようにします。デフォルトでは、標準実行が選択されています。

** * 状態 * を待ちます
+
コマンドの実行を待機する時間（秒）を指定できます。デフォルト値は 60 秒です。



* * 最小ソフトウェアバージョン *
+
コマンドが動作するために必要なソフトウェアの最小バージョンを指定します。たとえば、 clustered Data ONTAP 8.2.0 と vCenter 6.0 を使用できます。各バージョンがカンマで区切って表示されます。

* * 予約および確認スクリプトは元のコマンド * から保持します
+
クローニングするコマンドに最初に指定された予約および検証スクリプトを保持できます。





== [ コード ] タブ

コマンドのコードを編集できます。

* * 検出パラメータ *
+
PowerShell コードで定義されたパラメーターをパラメーター定義テーブルおよびパラメーターマッピングテーブルにコピーします。





== [ パラメーターを定義（ Parameters Definition ）

[ コード ] タブで入力したコードで定義されているパラメータを表示します。

* * 名前 *
+
パラメータの名前を表示します。

* * 概要 *
+
パラメータの概要 を表示します。

* * 必須 *
+
必須パラメータのチェックボックスを選択して表示します。

* * タイプ *
+
文字列や列挙などのパラメータのタイプを表示します。

* * 値 *
+
パラメータに設定されている値が表示されます。

* * パラメータを追加 *
+
選択したスクリプト言語が Perl の場合は、パラメータをコマンドに追加できます。

* * パラメーターを削除 *
+
選択したスクリプト言語が Perl の場合に、コマンドからパラメータを削除できます。





== [ パラメータマッピング（ Parameters Mapping ） ] タブ

パラメータをディクショナリオブジェクトにマッピングし、属性名とオブジェクト名を指定できます。

* * 名前 *
+
パラメータの名前を表示します。

* * タイプ *
+
パラメーターの辞書オブジェクトを選択できます。

* * 属性 *
+
必要な属性を指定できます。属性を選択するか（使用可能な場合）、属性の名前を入力できます。

* * オブジェクト名 *
+
ディクショナリオブジェクトの名前を指定できます。





== [ 予約 ] タブ

コマンドで必要なリソースをリザーブできます。

* * 予約スクリプト *
+
SQL クエリを入力して、コマンドで必要なリソースを予約できます。これにより、スケジュールされたワークフローの実行中に、必要なリソースを確実に使用できるようになります。

* * 予約リプレゼンテーション *
+
MVEL 構文を使用して、予約の文字列表現を指定できます。ストリング表現は、予約ウィンドウに予約の詳細を表示するために使用されます。





== [Verification （検証） ] タブ

予約を確認し、コマンド実行後に予約を削除できます。

* * 検証スクリプト *
+
リザベーションスクリプトで予約されたリソースの使用状況を確認するための SQL クエリを入力できます。また、検証スクリプトは WFA キャッシュが更新されているかどうかを検証し、キャッシュの取得後に予約を削除します。

* * テスト検証 *
+
検証ダイアログボックスを開きます。このダイアログボックスで、検証スクリプトのパラメータをテストできます。





== コマンドボタン

* * テスト *
+
<ScriptLanguage> ダイアログボックスのテストコマンド <CommandName> を開きます。このダイアログボックスで、コマンドをテストできます。

* * 保存 *
+
コマンドを保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


