---
permalink: help/reference-new-dictionary-entry-dialog-box.html 
sidebar: sidebar 
keywords: new, dictionary, entry, dialog box, enable, create, object, specify, definition 
summary: '[ 新しい辞書エントリ ] ダイアログボックスでは、新しい辞書オブジェクトを作成し、オブジェクトの定義を指定できます。' 
---
= [ 新しい辞書エントリ ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 新しい辞書エントリ ] ダイアログボックスでは、新しい辞書オブジェクトを作成し、オブジェクトの定義を指定できます。

* * オブジェクトタイプの名前 *
+
ディクショナリオブジェクトの名前を指定できます。

* * 概要 *
+
ディクショナリオブジェクトの概要 を指定できます。

* * スキーム *
+
オブジェクトに関連付けるスキームを選択できます。証明済みスキームにカスタム辞書エントリを追加できます。

* * エンティティバージョン *
+
辞書エントリのバージョン番号を 'major.minor.revision' 形式で入力できますたとえば '1.0.0 です





== 属性テーブル

ディクショナリオブジェクトを定義する属性のリストを指定できます。

* * 名前 *
+
属性の名前を入力できます。

* * タイプ *
+
文字列、ブーリアン、整数などの属性のタイプをチェック対象として選択できます。選択したスキームから辞書エントリを参照することもできます。

* * 文字列の長さ *
+
属性に対して文字列タイプが選択されている場合、文字列の長さを数字で指定できます。

* * 値 *
+
属性に対して enum タイプが選択されている場合、カンマ区切り値のリストを指定できます。

* * ナチュラルキー *
+
ディクショナリ属性がディクショナリオブジェクトのナチュラルキーの一部かどうかを指定できます。

+
ナチュラルキーは、ディクショナリオブジェクトの一意の識別子です。たとえば、 qtree は qtree 名、ボリューム名、アレイ IP アドレスで識別されます。

* * キャッシュされます。 *
+
属性をキャッシュするかどうかを指定できます。

+
ディクショナリエントリには、キャッシュされた属性とキャッシュされていない属性の両方を含めることができます。キャッシュテーブルが作成され、スキームのキャッシュ取得時にキャッシュ対象としてマークされた属性が表示されます。少なくとも 1 つの属性がキャッシュ対象として選択されている場合、ディクショナリオブジェクトのキャッシュテーブルが作成されます。

* * は null にできます *
+
属性の値を null にするかどうかを指定できます。この設定は、キャッシュ対象として選択された属性に対してのみ有効です。

* * 概要 *
+
属性の概要 を指定できます。

* * ナチュラルキーカラムの値では、大文字と小文字が区別されます。 *
+
ナチュラルキーでは大文字と小文字が区別されるように指定できます。

* * コマンドボタン *
+
** * 行を追加 *
+
属性の指定に使用するテーブルに行を追加できます。

** * 行を削除 *
+
選択した行を削除できます。




