---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: Edit Credentials ダイアログボックスでは、既存のクレデンシャルを変更できます。 
---
= Edit Credentials ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Edit Credentials ダイアログボックスでは、既存のクレデンシャルを変更できます。



== クレデンシャルパラメータ

* * マッチ *
+
クレデンシャルの一致タイプを選択できます。これにより、特定の IP アドレスまたはホスト名のクレデンシャル、またはサブネット全体または IP 範囲のクレデンシャルが定義されます。使用できるオプションは次のとおりです。

+
** Exact ：特定の IP アドレスまたはホスト名を定義します
** pattern ：サブネット全体または IP 範囲を定義します


* * タイプ *
+
ドロップダウンリストからクレデンシャルのタイプを選択できます。

+
VMware vCenter は Linux ではサポートされていません。

* * 名前 /IP *
+
クレデンシャルのホスト名または IP アドレスを指定できます。

* * ユーザー名 *
+
クレデンシャルのユーザ名を指定できます。

* * パスワード *
+
ユーザ名に対応するパスワードを指定できます。

* * デフォルト値を上書き *
+
クレデンシャルについて選択したリモートシステムタイプに関連付けられているプロトコル、ポート、およびタイムアウトのデフォルト値を上書きできます。

+
デフォルトでは、このチェックボックスは選択されていません。デフォルト値を上書きする場合は、チェックボックスを選択する必要があります。





== プロトコルテーブル

プロトコルテーブルには、選択したリモートシステムのクレデンシャルに関連付けられたプロトコルのポート番号とタイムアウト制限（秒）が表示されます。



== コマンドボタン

* * テスト *
+
必要なクレデンシャルを使用してログインすることで、ホスト名または IP アドレスへの接続をテストできます。

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


