---
permalink: help/reference-edit-active-directory-group-dialog-box.html 
sidebar: sidebar 
keywords: edit, active directory, dialog box, enable, view, modify, oncommand, workflow, automation, group 
summary: Active Directory グループの編集ダイアログボックスでは、 OnCommand Workflow Automation Active Directory グループの設定を表示および変更できます。 
---
= Edit Active Directory Group ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active Directory グループの編集ダイアログボックスでは、 OnCommand Workflow Automation Active Directory グループの設定を表示および変更できます。

Active Directory グループの権限とロールによっては、 Active Directory グループウィンドウにアクセスできない場合があります。ただし、「 * 設定 * 」を選択し、「 * 管理 * 」で「 * Active Directory グループ * 」をクリックして、 Active Directory グループの設定を編集することができます。


NOTE: 編集可能なフィールドは、 Active Directory グループの権限によって異なります。

* * グループ名 *
+
Active Directory グループのグループ名が表示されます。

* * 役割 *
+
ユーザアカウントに割り当てられているロールが表示されます。

+
Active Directory グループに割り当てられている次のいずれかのグループロールが表示されます。

+
** * ゲスト *
+
このグループは、ワークフロー実行のステータスのみを表示したり、ワークフロー実行のステータスの変更について通知したりすることができます。

** * 演算子 *
+
このグループでは、グループにアクセス権が付与されているワークフローをプレビューして実行できます。

** * 承認者 *
+
このグループでは、グループにアクセス権が付与されているワークフローをプレビュー、実行、承認、および拒否できます。

+

NOTE: 承認者の E メール ID と、承認者に通知するワークフローのステータスを入力する必要があります。複数の承認者がいる場合は、 [ 電子メール *] フィールドにグループ電子メール ID を入力できます。

** * 建築家 *
+
このグループには作成ワークフローへのフルアクセスがありますが、 WFA サーバのグローバル設定の変更は制限されます。

** * 管理者 *
+
このグループは WFA サーバへの完全なアクセス権を持っています。

+

NOTE: 管理者グループを少なくとも 1 つ設定する必要があります。



* * 電子メール *
+
[*Notify On*] オプションが選択されている場合に通知が送信される Active Directory グループの電子メールを指定します。

* * 通知オン *
+
Active Directory グループによってトリガーされるワークフローの実行中に、 Active Directory グループに E メールで通知するタイミングを選択できます。次のオプションを任意に組み合わせて選択できます。

+
** ワークフローの実行が開始されました : ワークフローの実行が開始されたときにユーザーに通知します
** ワークフローの実行に失敗した / 部分的に成功した：ワークフローの実行に失敗した場合、または 1 つ以上のステップが失敗した場合でもワークフローが正常に実行された場合に、ユーザーに通知します。
+
失敗したステップが、そのステップが失敗してもワークフローを続行できるように設定されているため、実行は完了しました。

** ワークフローの実行が正常に完了しました：ワークフローの実行が正常に完了したことをユーザに通知します。
** 承認待ちのワークフローの実行： WFA の設定によっては、 Operator ユーザまたは Architect ユーザからの承認を待っているワークフローが実行された場合にユーザに通知します。






== コマンドボタン

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


