---
permalink: help/reference-row-repetition-details-dialog-box.html 
sidebar: sidebar 
keywords: row, repetition, details, dialog box, enable, specify, parameters, row, repeated 
summary: 行繰り返しの詳細（ Row Repetition Details ）ダイアログボックスでは、行のパラメーターを繰り返す方法を指定できます。 
---
= [ 行の繰り返しの詳細 ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
行繰り返しの詳細（ Row Repetition Details ）ダイアログボックスでは、行のパラメーターを繰り返す方法を指定できます。



== 繰り返し

必要な繰り返しオプションのタイプを選択できます。デフォルトでは、回数 * オプションが選択されています。

* * 回数 *
+
次の項目を指定できます。

+
** 特定の行を実行する回数
** インデックス変数（ Index Variable ）
** 変数（ variables ）
** * 回数 *
+
特定の行を実行する回数を指定できます。

** * インデックス変数 *
+
行の繰り返しに使用するインデックス変数の名前を指定できます。

** * 変数 *
+
行の繰り返し中に使用する必要がある追加の変数を含めることができます。

+
*** * 追加 * 。
+
変数テーブルに新しい行を追加します。

*** * 削除 *
+
選択した行を変数テーブルから削除します。





* * グループ内のすべてのリソース *
+
次の項目を指定できます。

+
** リソースタイプ（ Resource Type ）
** リソース検索条件
** リソース変数（ Resource Variable ）
** インデックス変数（ Index Variable ）
** グループサイズ変数
** 変数（ variables ）
** * リソースタイプ *
+
リソースタイプを選択できます。

** * リソース検索条件 *
+
[ リソースを選択（ Resource Selection ） ] ダイアログボックスを開きます。このダイアログボックスでは、選択したリソースタイプのリソースを検索するための条件を指定できます。指定した条件に基づいて、検索された各リソースに対してループが実行されます。

** * リソース変数 *
+
リソース変数の名前を入力できます。

** * インデックス変数 *
+
行の繰り返しのインデックスを指定できます。

** * グループサイズ変数 *
+
グループサイズ変数の名前を入力できます。

** * 変数 *
+
行の繰り返し中に使用する必要がある追加の変数を含めることができます。



* * コマンドボタン *
+
** * OK *
+
設定を保存してダイアログボックスを閉じます。

** * キャンセル *
+
変更がある場合は保存されず、ダイアログボックスが閉じます。




