---
permalink: help/reference-edit-remote-system-type-dialog-box.html 
sidebar: sidebar 
keywords: edit, remote, system, type, dialog box, enable, modify, name, description, version, protocol, default port, timeout, existing, certified 
summary: Edit Remote System Type ダイアログボックスでは、名前、概要 、バージョン、プロトコル、デフォルトポートを変更できます。 既存のリモートシステムタイプのデフォルトタイムアウト。ネットアップ認定リモートシステムのタイプは変更できません。 
---
= Edit Remote System Type （リモートシステムタイプの編集）ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Edit Remote System Type ダイアログボックスでは、名前、概要 、バージョン、プロトコル、デフォルトポートを変更できます。 既存のリモートシステムタイプのデフォルトタイムアウト。ネットアップ認定リモートシステムのタイプは変更できません。

* [ 詳細 ] タブ
* [ 検証スクリプト ] タブ




== [ 詳細 ] タブ

名前、概要 、バージョン、接続プロトコルなど、リモートシステムタイプの詳細を編集できます。

* * 名前 *
+
リモートシステムタイプの名前を編集できます。

* * 概要 *
+
リモートシステムタイプの概要 を変更できます。

* * バージョン *
+
リモート・システム・タイプのバージョン番号を 'major.minor.revision 形式で編集できますたとえば '1.0.0 のようになります

* * 接続プロトコル *
+
リモートシステムに接続する際に OnCommand Workflow Automation （ WFA ）で使用する次のプロトコルのいずれかを選択できます。

+
** HTTPS を HTTP にフォールバックします
+
接続では主に HTTPS が使用されます。HTTPS 経由の接続に失敗した場合は、 HTTP が使用されます。HTTP 経由の接続にも失敗した場合、接続試行は破棄されます。

** HTTPS のみ
** HTTP のみ
** カスタム




接続プロトコルを選択すると、プロトコル、デフォルトポート、およびデフォルトタイムアウト（秒）フィールドにデータが入力されます。



== [ 検証スクリプト ] タブ

リモートシステムの接続をテストするための検証スクリプトを指定できます。検証スクリプトは Perl で記述する必要があり、 checkCredentials 関数（ $host 、 $user 、 $password 、 $protocol 、 $port ）を含める必要があります。 $timeout.` 検証中に、 WFA は checkCredentials 機能を呼び出します。この機能には、リモートシステムタイプと接続プロトコルに対して設定された値が使用されます。この関数は ' 接続の検証に成功した場合は値 1' 接続の検証に失敗した場合は 0 を返します

接続をテストするスクリプトを実行するには、 * Perl スクリプトのテスト * をクリックします。



== コマンドボタン

* * 保存 *
+
リモートシステムタイプの変更された設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


