---
permalink: help/task-configure-snmp-version-3.html 
sidebar: sidebar 
keywords: configure, oncommand, workflow, automation, simple, network, management, protocol, version 3, traps, about, status, operations 
summary: また、ワークフロー処理のステータスに関する簡易ネットワーク管理プロトコル（ SNMP ）バージョン 3 トラップを送信するように OnCommand Workflow Automation （ WFA ）を設定することもできます。 
---
= SNMP バージョン 3 を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
また、ワークフロー処理のステータスに関する簡易ネットワーク管理プロトコル（ SNMP ）バージョン 3 トラップを送信するように OnCommand Workflow Automation （ WFA ）を設定することもできます。

* このタスクについて *

バージョン 3 には、次の 2 つの追加セキュリティオプションがあります。

* バージョン 3 、認証あり
+
トラップは、暗号化されていないネットワーク経由で送信されますSNMP トラップメッセージと同じ認証パラメータで設定された SNMP 管理アプリケーションは、トラップを受信できます。

* バージョン 3 、認証と暗号化を使用
+
トラップはネットワーク上で暗号化されて送信されます。これらのトラップを受信して復号化するには、 SNMP トラップと同じ認証パラメータと暗号化キーを使用して SNMP 管理アプリケーションを設定する必要があります。



.手順
. Web ブラウザで admin ユーザとして WFA にログインし、 WFA サーバにアクセスします。
. [ * 設定 * ] をクリックし、 [ * 設定 * ] で [* SNMP] をクリックします。
. [Enable SNMP*] チェックボックスをオンにします。
. [* バージョン *] ドロップダウンリストで、次のいずれかのオプションを選択します。
+
** バージョン 3
** バージョン 3 、認証あり
** バージョン 3 、認証と暗号化を使用


. 手順 4 で選択した特定の SNMP バージョン 3 オプションに対応する SNMP 設定オプションを選択します。
. 管理ホストの IPv4 アドレス、 IPv6 アドレス、またはホスト名とポート番号を入力します。WFA は、指定されたポート番号に SNMP トラップを送信します。デフォルトのポート番号は 162 です。
. [ * 通知オン * ] セクションで、次のチェックボックスの 1 つ以上を選択します。
+
** ワークフロー計画の開始 / 失敗 / 完了
** ワークフローの実行を開始しました
** ワークフローの実行が完了しました
** ワークフローの実行に失敗しました
** 承認待ちのワークフローを実行しています
** 取得に失敗しました


. [ テスト通知の送信 *] をクリックして、設定を確認します。
. [ 保存（ Save ） ] をクリックします。

