---
permalink: workflows/concept-overview-of-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, software, solution, automate, storage, management, tasks, provisioning, migration, decommissioning, data, protection, configurations, cloning, build, complete, specified, processes 
summary: OnCommand Workflow Automation （ WFA ）は、プロビジョニング、移行、運用停止、データ保護設定などのストレージ管理タスクの自動化に役立つソフトウェア解決策 です。 およびストレージのクローニングWFA を使用すると、プロセスで指定されたタスクを実行するためのワークフローを構築できます。 
---
= OnCommand Workflow Automation の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）は、プロビジョニング、移行、運用停止、データ保護設定などのストレージ管理タスクの自動化に役立つソフトウェア解決策 です。 およびストレージのクローニングWFA を使用すると、プロセスで指定されたタスクを実行するためのワークフローを構築できます。

ワークフローは繰り返し実行される手順のタスクで、次の種類のタスクを含む一連の手順で構成されます。

* データベースまたはファイルシステム用のストレージのプロビジョニング、移行、または運用停止
* ストレージスイッチやデータストアなど、新しい仮想化環境をセットアップする
* エンドツーエンドのオーケストレーションプロセスの一環としてアプリケーション用のストレージをセットアップする


ストレージアーキテクトは、次のような、ベストプラクティスに従い、組織の要件を満たすワークフローを定義できます。

* 必要な命名規則を使用します
* ストレージオブジェクトに一意のオプションを設定しています
* リソースを選択する
* 内部構成管理データベース（ CMDB ）とチケット処理アプリケーションを統合する




== WFA の機能

* ワークフローを構築するためのワークフロー設計ポータル
+
ワークフロー設計ポータルには、コマンド、テンプレート、ファインダ、フィルタ、 ワークフローの作成に使用される関数です。設計者は、自動リソース選択、行の繰り返し（ループ）、承認ポイントなどの高度な機能をワークフローに含めることができます。

+
ワークフローデザインポータルには、外部システムからデータをキャッシュするための、ディクショナリエントリ、キャッシュクエリ、データソースタイプなどのビルディングブロックも含まれています。

* 実行ポータル：ワークフローの実行、ワークフローの実行ステータスの確認、ログへのアクセスを行います
* WFA の設定、データソースへの接続、ユーザクレデンシャルの設定などのタスクの管理 / 設定オプション
* Web サービスインターフェイスを使用して、外部ポータルやデータセンターオーケストレーションソフトウェアからワークフローを起動できます
* Storage Automation Store で WFA パックをダウンロードしてください。ONTAP 9.7.0 パックは WFA 5.1 にバンドルされています。




== WFA ライセンス情報

OnCommand Workflow Automation サーバを使用するために必要なライセンスはありません。
