---
permalink: workflows/concept-what-data-sources-are.html 
sidebar: sidebar 
keywords: data, source, method, establishing, connection, systems, files, databases, order, extract, example, active iq, unified manager 9.4, type 
summary: データソースは、データを抽出するために、他のシステム、ファイル、およびデータベースとの接続を確立する手段の 1 つです。たとえば、データソースは、 Active IQ Unified Manager 9.4 データソースタイプの Active IQ Unified Manager データベースに接続できます。 
---
= データソースとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データソースは、データを抽出するために、他のシステム、ファイル、およびデータベースとの接続を確立する手段の 1 つです。たとえば、データソースは、 Active IQ Unified Manager 9.4 データソースタイプの Active IQ Unified Manager データベースに接続できます。

キャッシング方式、必要なポート、およびデータソースタイプとデータソースタイプを関連付けることで、データ収集に必要なデータソースタイプを定義したあとで、 OnCommand Workflow Automation （ WFA ）にカスタムデータソースを追加できます。

WFA は、さまざまなデータソースを介して情報をキャッシュします。WFA は、データソースからリソース情報を収集し、キャッシュ方式に対応するようにフォーマットします。キャッシュスキーム内のテーブルであるキャッシュテーブルは、ディクショナリエントリオブジェクトと一致するようにフォーマットされます。ワークフローで Finder を使用すると、ディクショナリオブジェクトが返され、ディクショナリオブジェクトのデータがキャッシュテーブルから取り込まれます。データソースからデータを取得するプロセスを、 _data source acquisition _ と呼びます。データソースの取得には、スクリプトベースまたはドライバベースの方法を使用できます。ソース間で違いが生じることがあり、データソースの取得時に異なる間隔でサンプルが収集されることがあります。WFA はその情報をデータベースにマージし、予約データをスーパーインポーズしてデータベース内の更新されたリソース情報を維持します。

WFA データベースには、いくつかの異なるキャッシュ方式があります。キャッシュスキームはテーブルのセットで、各テーブルには特定のディクショナリエントリタイプの情報が含まれます。ただし、テーブルには、特定のデータソースタイプの複数のソースからの情報が結合されている場合があります。WFA では、データベース情報を使用して、リソースのステータスを把握し、計算を実行し、リソースに対してコマンドを実行します。
