---
permalink: workflows/concept-what-dictionary-entries-are.html 
sidebar: sidebar 
keywords: dictionary, entries, oncommand, workflow, automation, building, blocks, use, represent, object, types, relationships, storage, environments, filters, return, value, natural, keys 
summary: ディクショナリエントリは、 OnCommand Workflow Automation （ WFA ）のビルディングブロックの 1 つです。ディクショナリエントリを使用して、ストレージ環境とストレージ関連環境におけるオブジェクトタイプとその関係を表すことができます。その後、ワークフローでフィルタを使用して、ディクショナリエントリの自然キーの値を返すことができます。 
---
= ディクショナリエントリとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディクショナリエントリは、 OnCommand Workflow Automation （ WFA ）のビルディングブロックの 1 つです。ディクショナリエントリを使用して、ストレージ環境とストレージ関連環境におけるオブジェクトタイプとその関係を表すことができます。その後、ワークフローでフィルタを使用して、ディクショナリエントリの自然キーの値を返すことができます。

ディクショナリエントリは、 WFA でサポートされるオブジェクトタイプの定義です。各ディクショナリエントリは、サポートされているストレージおよびストレージ関連の環境で、オブジェクトタイプとその関係を表します。ディクショナリオブジェクトは、タイプチェックの可能性がある属性のリストで構成されます。完全な値を持つディクショナリオブジェクトは、型のオブジェクトインスタンスを記述します。また、参照属性は、オブジェクトと環境との関係を記述します。たとえば、ボリューム辞書オブジェクトには name 、 size_MB 、 volume_guarantee などの多数の属性があります。また、ボリュームディクショナリオブジェクトには、アグリゲートへの参照、およびボリュームを含むアレイへの参照が array_id および aggregate_id の形式で含まれます

オブジェクトのキャッシュテーブルは、キャッシュ用にマークされたディクショナリエントリの属性の一部またはすべてを含むデータベースです。ディクショナリエントリにキャッシュテーブルを含めるには、少なくとも 1 つのディクショナリエントリの属性をキャッシュ用にマークする必要があります。ディクショナリエントリには、オブジェクトの一意の識別子であるナチュラルキーが含まれます。たとえば、 7-Mode ボリュームは、それらのボリュームを含むアレイの名前と IP アドレスによって一意に識別されます。qtree は、 qtree 名、ボリューム名、およびアレイ IP アドレスによって識別されます。ディクショナリエントリを作成するときに、ディクショナリエントリのナチュラルキーの一部であるディクショナリ属性を識別する必要があります。
