---
permalink: workflows/reference-guidelines-for-commands.html 
sidebar: sidebar 
keywords: must, aware, guidelines, create, commands, oncommand, workflow, automation 
summary: OnCommand Workflow Automation （ WFA ）でコマンドを作成する際のガイドラインに注意する必要があります。 
---
= コマンドのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）でコマンドを作成する際のガイドラインに注意する必要があります。

[cols="2*"]
|===
| ガイドライン | 例 


 a| 
コマンドには、わかりやすい名前を使用します。
 a| 
qtree を作成します



 a| 
単語を区切るにはスペースを使用します。各単語は大文字で始まる必要があります。
 a| 
「ボリュームを作成」



 a| 
オプションパラメータで想定される結果など、コマンドの機能について説明する概要 を提供します。
 a| 
なし



 a| 
デフォルトでは、標準コマンドのタイムアウトは 600 秒です。コマンドの作成時にデフォルトのタイムアウトが設定されます。デフォルト値を変更するのは、コマンドの完了に時間がかかる場合だけにしてください。
 a| 
[Create Volume] コマンドを使用します



 a| 
長時間の処理の場合は、 2 つのコマンドを作成します。 1 つは長時間の処理を実行するコマンドで、もう 1 つは処理の進捗状況を定期的に報告するコマンドです。最初のコマンドは「標準実行」コマンドタイプで、 2 番目のコマンドは「条件を待機」コマンドタイプである必要があります。
 a| 
'Create VSM' および 'Wait for VSM' コマンド



 a| 
容易に識別できるように 'wait for condition' コマンド名の前には 'wait' を付けます
 a| 
「 CM ボリューム移動の待機」



 a| 
「条件の待機」コマンドに適切な待機間隔を使用します。指定した値は、長時間の処理が完了したかどうかを確認するためにポーリングコマンドが実行される間隔を制御します。
 a| 
'Wait for VSM' コマンドの 60 秒のサンプリング間隔



 a| 
「条件待機」コマンドでは、長時間実行動作が完了するまでの予想時間に基づいて適切なタイムアウトを使用します。ネットワーク経由のデータ転送を実行する場合は、想定時間が大幅に長くなる可能性があります。
 a| 
VSM ベースライン転送が完了するまでに数日かかることがあります。したがって、指定されたタイムアウトは 6 日です。

|===


== 文字列表現

コマンドの文字列表現は、計画および実行中にワークフロー設計内のコマンドの詳細を表示します。コマンドの文字列表現で使用できるのは、コマンドパラメータだけです。

[cols="2*"]
|===
| ガイドライン | 例 


 a| 
値のない属性は使用しないでください。値のない属性は NA と表示されます。
 a| 
volname 10.68.66.212 [NA]aggr1 / testVol7



 a| 
文字列表現では、 [],/ の区切り記号を使用して異なるエントリを区切ります。
 a| 
`_ArrayName [ArrayIp]_`



 a| 
文字列表現のすべての値に意味のあるラベルを指定します。
 a| 
`_Volume name=VolumeName_`

|===


== コマンド定義言語

コマンドは、次のサポートされているスクリプト言語を使用して記述できます。

* PowerShell
* Perl の場合




== コマンドパラメータの定義

コマンドパラメータは、名前（ Name ）、パラメータ（概要 ）、タイプ（ Type ）、パラメータのデフォルト値、およびパラメータが必須かどうかによって記述されます。パラメータタイプは、 String 、 Boolean 、 Integer 、 Long 、 Double 、 列挙、日時、容量、アレイ、ハッシュテーブル、 パスワード、または XmlDocument 。ほとんどの型の値は直感的ですが、 Array と Hashtable の値は次の表に示す特定の形式にする必要があります。

[cols="2*"]
|===
| ガイドライン | 例 


 a| 
Array 入力タイプの値がカンマで区切った値のリストであることを確認します。
 a| 
[listing]
----
[parameter(Mandatory=$false,
HelpMessage="Months in which the schedule executes.")]
[array]$CronMonths
----
入力は 0 、 3 、 6 、 9 のように渡されます



 a| 
Hashtable 入力型の値が、セミコロンで区切られた key= 値のペアのリストであることを確認します。
 a| 
[listing]
----
[parameter(Mandatory=$false,
HelpMessage="Volume names and size (in MB)")]
[hashtable]$VolumeNamesAndSize
----
指定するパスは、次のとおりです。ボリューム 1 = 100 、ボリューム 2 = 250 、ボリューム 3 = 50

|===