---
permalink: workflows/reference-considerations-of-importing-wfa-content.html 
sidebar: sidebar 
keywords: aware, certain, considerations, import, user-created, content, exported, oncommand, workflow, automation, installation, content, downloaded, storage, store, community 
summary: ユーザが作成したコンテンツ、別の OnCommand Workflow Automation （ WFA ）インストールからエクスポートされたコンテンツ、または Storage Automation Store または WFA コミュニティからダウンロードしたコンテンツをインポートする場合は、一定の考慮事項に注意する必要があります。 
---
= OnCommand Workflow Automation コンテンツをインポートする際の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザが作成したコンテンツ、別の OnCommand Workflow Automation （ WFA ）インストールからエクスポートされたコンテンツ、または Storage Automation Store または WFA コミュニティからダウンロードしたコンテンツをインポートする場合は、一定の考慮事項に注意する必要があります。

* WFA のコンテンツは「 .dar 」ファイルとして保存されます。また、ユーザが作成したコンテンツ全体を別のシステムや、ワークフロー、ファインダ、コマンド、ディクショナリなどの特定の項目に含めることができます。
* 既存のカテゴリが '.dar ファイルからインポートされると ' インポートされたコンテンツがカテゴリ内の既存のコンテンツとマージされます
+
たとえば、 WFA サーバのカテゴリ A には 2 つのワークフロー WF1 および WF2 があるとします。カテゴリ A のワークフロー WF3 および Wf4 を WFA サーバにインポートすると、カテゴリ A にはインポート後にワークフロー WF1 、 WF2 、 WF3 、および Wf4 が含まれます。

* 「 .dar 」ファイルにディクショナリエントリが含まれている場合、ディクショナリエントリに対応するキャッシュテーブルが自動的に更新されます。
+
キャッシュテーブルが自動的に更新されない場合は、「 wfa_log 」ファイルにエラーメッセージが記録されます。

* WFA サーバに存在しないパックに依存する「 .dar 」ファイルをインポートすると、 WFA は、エンティティに関連するすべての依存関係が満たされているかどうかを確認しようとします。
+
** 1 つ以上のエンティティが見つからない場合や、エンティティの下位バージョンが見つかった場合、インポートは失敗し、エラーメッセージが表示されます。
+
エラーメッセージには、依存関係を満たすためにインストールする必要があるパックの詳細が表示されます。

** 上位バージョンのエンティティが見つかった場合や、証明書が変更された場合は、バージョン不一致に関する一般的なダイアログボックスが表示され、インポートが完了します。
+
バージョン不一致の詳細は 'wfa_log' ファイルに記録されます



* 次の項目についての質問やサポートリクエストは、 WFA コミュニティに送信される必要があります。
+
** WFA コミュニティからダウンロードされたすべてのコンテンツ
** 作成したカスタムの WFA コンテンツ
** 変更した WFA のコンテンツ



