---
permalink: workflows/reference-guidelines-for-workflows.html 
sidebar: sidebar 
keywords: aware, guidelines, create, modify, predefined, workflow, oncommand, workflow, automation 
summary: OnCommand Workflow Automation （ WFA ）の事前定義されたワークフローの作成または変更に関するガイドラインを確認しておく必要があります。 
---
= ワークフローのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）の事前定義されたワークフローの作成または変更に関するガイドラインを確認しておく必要があります。



== 一般的なガイドライン

[cols="2*"]
|===
| ガイドライン | 例 


 a| 
ストレージオペレータが実行した処理が反映されるように、ワークフローに名前を付けます。
 a| 
CIFS 共有を作成します



 a| 
ワークフロー名では、最初の単語の最初の文字とオブジェクトであるすべての単語を大文字にします。略語や頭字語の文字を大文字にします。
 a| 
ボリューム

qtree

clustered Data ONTAP の qtree CIFS 共有を作成



 a| 
ワークフローの説明には、ワークフローの前提条件、ワークフローの結果、または条件付きの実行など、ワークフローのすべての重要な手順を含めます。
 a| 
前提条件を含むサンプルワークフロー「 clustered Data ONTAP ストレージでの VMware NFS データストアの作成」の概要 を参照してください。



 a| 
ワークフローがプロダクションの準備ができていて、ポータルページに表示できる場合にのみ、「 Ready for Production 」を「 true 」に設定します。
 a| 
なし



 a| 
デフォルトでは ' 予約済み要素の考慮を true に設定します実行用のワークフローをプレビューするとき、 WFA プランナーは、キャッシュデータベース内の既存のオブジェクトと一緒に予約されているすべてのオブジェクトを考慮します。このオプションを「 true 」に設定すると、特定のワークフローを計画するときに、他のスケジュールされたワークフローまたは並列実行ワークフローの影響が考慮されます
 a| 
* シナリオ 1
+
ワークフロー 1 ではボリュームを作成し、 1 週間後に実行するようにスケジュール設定します。ワークフロー 2 では、検索対象のボリュームに qtree または LUN が作成されます。ワークフロー 2 が 1 日以内に実行される場合、ワークフロー 2 で「予約済み要素の考慮」をオフにして、 1 週間に作成するボリュームを考慮しないようにする必要があります。

* シナリオ 2
+
ワークフロー 1 では 'Create Volume' コマンドを使用しますスケジュール設定されたワークフロー 2 でアグリゲートの 100GB を消費する場合は、計画段階でワークフロー 2 の要件を考慮する必要があります。





 a| 
デフォルトでは、「エレメントの存在検証を有効にする」は「真」に設定されています
 a| 
* シナリオ 1
+
ボリュームが存在する場合にのみ ' ボリュームを削除コマンドを使用してボリュームを名前で削除するワークフローを作成し ' そのボリュームを作成ボリュームまたはクローンボリュームなどの別のコマンドを使用して再作成する場合 ' ワークフローではこのフラグを使用しないでくださいボリュームを削除した場合の効果は 'Create volume コマンドでは使用できないため ' ワークフローは失敗します

* シナリオ 2
+
Create Volume コマンドは ' vol198` という名前のワークフローで使用されます

+
このオプションが true に設定されている場合、 WFA プランナーは、計画時に、その名前を使用してボリュームが特定のアレイに存在するかどうかを確認します。計画中にボリュームが存在するとワークフローが失敗します。





 a| 
ワークフローで同じコマンドを複数回選択する場合は、コマンドインスタンスに適切な表示名を指定します。
 a| 
サンプル・ワークフローでは 'Create Volume' コマンドを 2 回使用して 'LUN の作成 ' マッピング ' 保護を SnapVault で行いますただし ' プライマリ・ボリュームとミラー・デスティネーション・ボリュームには ' プライマリ・ボリュームの作成とセカンダリ・ボリュームの作成が適切に使用されます

|===


== ユーザ入力

[cols="2*"]
|===
| ガイドライン | 例 


 a| 
名前：

* 名前の先頭には「 $` 」文字を付けます。
* 各単語の先頭に大文字を使用します。
* すべての用語や略語に大文字を使用します。
* アンダースコアは使用しないでください。

 a| 
「 $Array 」

「 $VolumeName 」



 a| 
表示名：

* 各単語の先頭に大文字を使用します。
* 単語をスペースで区切ります。
* 入力に特定の単位がある場合は、表示名に角かっこで囲んで単位を指定します。

 a| 
「ボリューム名」

「ボリューム・サイズ（ MB ）」



 a| 
説明：

* ユーザ入力ごとにわかりやすい概要 を指定します。
* 必要に応じて例を挙げてください。
+
これは、特にユーザ入力が特定の形式であると想定される場合に実行してください。



ユーザー入力の説明は、ワークフローの実行中にユーザー入力のツールチップとして表示されます。
 a| 
「 igroup 」に追加するイニシエータたとえば、イニシエータの IQN や WWPN などです。



 a| 
Type ：入力を特定の値セットに制限する場合は、タイプとして Enum を選択します。
 a| 
プロトコル : "iSCSI`", "FCP `", "MIXED `"



 a| 
Type ：ユーザが WFA キャッシュの値から選択できる場合は、タイプとして Query を選択します。
 a| 
$Array: クエリのクエリタイプ :

[listing]
----
SELECT
	ip, name
FROM
	storage.array
----


 a| 
[ タイプ ]: ユーザー入力がクエリから取得した値に制限されているか、サポートされている列挙型のみに制限されている必要がある場合に、ユーザー入力をロック済みとしてマークします。
 a| 
$Array ：ロックされたクエリタイプ：キャッシュ内のアレイのみ選択できます。 $Protocol ：有効な値が iSCSI 、 FCP 、 mixed のロックされた Enum タイプです。有効な値以外の値はサポートされません。



 a| 
タイプ：クエリタイプクエリ演算子がユーザ入力を適切に選択できるようになると、クエリに戻り値として列を追加できます。
 a| 
$ Aggregate ：アグリゲートを選択する前に属性を確認できるように、名前と合計サイズ、使用可能なサイズを指定します。



 a| 
タイプ：クエリータイプユーザ入力の SQL クエリーは、その前にある他のユーザ入力を参照できます。この機能を使用すると、アレイの vFiler ユニット、アグリゲートのボリューム、 Storage Virtual Machine （ SVM ）の LUN など、他のユーザ入力に基づいてクエリの結果を制限できます。
 a| 
サンプル・ワークフローでは 'Create a Clustered Data ONTAP Volume] で 'VserverName のクエリは次のようになります

[listing]
----
SELECT
    vserver.name
FROM
    cm_storage.cluster cluster,
    cm_storage.vserver vserver
WHERE
    vserver.cluster_id = cluster.id
    AND cluster.name = '${ClusterName}'
    AND vserver.type = 'cluster'
ORDER BY
    vserver.name ASC
----
クエリは $ \ ｛ clustername ｝ を参照します。 $clustername は、 $VserverName ユーザ入力の前に入力されたユーザ名です。



 a| 
type ：ブール型を使用し、ブール型の値を "true 、 false" として使用します。これにより、ユーザ入力を直接使用して、ワークフロー設計で内部式を記述できます。たとえば、 $UserInputName='Yes' ではなく $UserInputName とします。
 a| 
$CreateCIFSShare: 有効な値が「 true 」または「 false 」のブール型



 a| 
[ タイプ ]: 文字列および数値型の場合、特定の形式で値を検証するときは、 [ 値 ] 列で正規表現を使用します。

IP アドレスとネットワークマスクの入力には正規表現を使用します。
 a| 
場所に固有のユーザ入力は、「 [A-Z ][A-Z ]\-0[1-9]` 」と表現できます。このユーザー入力は "US -01`" 、 "NB-02`" などの値を受け入れますが、 "nb-00`" は受け入れません。



 a| 
[ タイプ ]: 数値タイプの場合、 [ 値 ] 列で範囲ベースの検証を指定できます。
 a| 
作成する LUN の数については、「値」列のエントリは 1~20 です。



 a| 
グループ：グループに関連するユーザが該当するバケットに入力し、グループに名前を付けます。
 a| 
ストレージ関連のすべてのユーザー入力用の「ストレージの詳細」。VMware 関連のすべてのユーザー入力の「データストアの詳細」。



 a| 
必須：ワークフローを実行するためにユーザ入力の値が必要な場合は、ユーザ入力を必須としてマークします。これにより、ユーザ入力画面がユーザからの入力を受け入れられるようになります。
 a| 
「 Create NFS Volume 」ワークフローの「 $VolumeName 」



 a| 
デフォルト値：ユーザ入力にデフォルト値があり、ほとんどのワークフロー実行で有効な場合は、値を指定します。これにより、デフォルトで目的が達成された場合に、実行中に入力を減らすことができます。
 a| 
なし

|===


== 定数、変数、および戻りパラメータ

|===


| ガイドライン | 例 


 a| 
定数 : 複数のコマンドにパラメータを定義するために共通の値を使用する場合は、定数を定義します。
 a| 
SnapVault サンプル・ワークフローでの LUN の作成 ' マッピング ' 保護については '_aggregate_Oオーバー コミットメント _threshold_ を参照してください



 a| 
定数 : 名前

* 各単語の先頭に大文字を使用します。
* すべての用語や略語に大文字を使用します。
* アンダースコアは使用しないでください。
* 定数名のすべての文字に大文字を使用します。

 a| 
_aggregate_Used_space_threshold_

_ActualVolumeSizeInMB_



 a| 
変数：コマンドパラメータのいずれかのボックスで定義されたオブジェクトに名前を指定します。変数は自動的に生成される名前で、変更できます。
 a| 
なし



 a| 
変数：変数名には小文字を使用します。
 a| 
ボリューム 1

cifs_share



 a| 
戻りパラメータ：ワークフローの計画と実行で、計画中に計算値または選択した値が返される場合は、戻りパラメータを使用します。ワークフローが Web サービスから実行されたときにも、プレビューモードで値が使用可能になります。
 a| 
アグリゲート：リソース選択ロジックを使用してアグリゲートを選択した場合、選択した実際のアグリゲートを戻りパラメータとして定義できます。

|===