---
permalink: workflows/task-test-the-wfa-reservation-script-for-commands.html 
sidebar: sidebar 
keywords: test, reservation, scripts, written, oncommand, workflow, automation, commands, playground, database, ensure, affect, table 
summary: OnCommand Workflow Automation （ WFA ）コマンド用に開発した予約スクリプトをプレイグランドデータベースでテストすることで、スクリプトが正常に動作していて WFA データベーステーブルに影響していないことを確認できます。 
---
= 予約スクリプトでコマンドをテストします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）コマンド用に開発した予約スクリプトをプレイグランドデータベースでテストすることで、スクリプトが正常に動作していて WFA データベーステーブルに影響していないことを確認できます。

.このタスクについて
WFA のデフォルトのインストールパスは、この手順 で使用されます。インストール時にデフォルトの場所を変更した場合は、変更した WFA のインストールパスを使用する必要があります。

.手順
. WFA サーバでコマンドプロンプトを開き、ディレクトリを「 c ： \Program Files\NetApp\WFA\mysql\mysql\bin 」に変更します
. 次のコマンドを使用して、 WFA データベースのダンプを作成します。 mysqldump -u wfa -pWfa123 --single-transaction --skip-add-drop-table database-tables > dump_location`
+
cm_storage データベーステーブルのダンプを作成するコマンド： mysqldump -u wfa -pWfa123 --single-transaction --skip-add-drop -tablecm_storage>c ： /tmp\cmSt2.sql

. 次のコマンドを使用して、作成したダンプを WFA のプレイグラウンドデータベースにリストアします。「 mysql -u wfa -pWfa123 遊び場 <dump_location`
+
「 mysql -u wfa -pWfa123 プレイグラウンド」 <c ： \tmp\cmSt2.sql

. WFA コマンドを作成または編集し、予約スクリプトを「 * Reservation * 」タブに書き込みます。
+
予約および検証スクリプトでプレイグラウンドデータベースのみが使用されていることを確認する必要があります。

. ワークフローを作成または編集し、ワークフローにコマンドを含めてから、ワークフローを実行します。
. リザベーションスクリプトと検証スクリプトが想定どおりに動作していることを確認します。
+
WFA のデータソースの取得プロセスでプレイグラウンドデータベースが更新されない。コマンドで作成した予約は手動で削除する必要があります。


